name: robot_engine
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/dzylikecode/robot_engine

environment:
  sdk: ^3.11.1

workspace:
  - packages/*

dependencies:
  raylib_c_translator: ^0.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
