// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'core_proxy.dart' as proxy;
import 'raylib_const.dart';
import 'structs.dart';
import 'dart:typed_data';


// Window-related functions
/// Initialize window and OpenGL context
const InitWindow = proxy.InitWindow;
/// Close window and unload OpenGL context
const CloseWindow = proxy.CloseWindow;
/// Check if application should close (KEY_ESCAPE pressed or windows close icon clicked)
bool WindowShouldClose() => raw.WindowShouldClose();
/// Check if window has been initialized successfully
bool IsWindowReady() => raw.IsWindowReady();
/// Check if window is currently fullscreen
bool IsWindowFullscreen() => raw.IsWindowFullscreen();
/// Check if window is currently hidden
bool IsWindowHidden() => raw.IsWindowHidden();
/// Check if window is currently minimized
bool IsWindowMinimized() => raw.IsWindowMinimized();
/// Check if window is currently maximized
bool IsWindowMaximized() => raw.IsWindowMaximized();
/// Check if window is currently focused
bool IsWindowFocused() => raw.IsWindowFocused();
/// Check if window has been resized last frame
bool IsWindowResized() => raw.IsWindowResized();
/// Check if one specific window flag is enabled
const IsWindowState = proxy.IsWindowState;
/// Set window configuration state using flags
const SetWindowState = proxy.SetWindowState;
/// Clear window configuration state flags
const ClearWindowState = proxy.ClearWindowState;
/// Toggle window state: fullscreen/windowed, resizes monitor to match window resolution
void ToggleFullscreen() => raw.ToggleFullscreen();
/// Toggle window state: borderless windowed, resizes window to match monitor resolution
void ToggleBorderlessWindowed() => raw.ToggleBorderlessWindowed();
/// Set window state: maximized, if resizable
void MaximizeWindow() => raw.MaximizeWindow();
/// Set window state: minimized, if resizable
void MinimizeWindow() => raw.MinimizeWindow();
/// Restore window from being minimized/maximized
void RestoreWindow() => raw.RestoreWindow();
/// Set icon for window (single image, RGBA 32bit)
const SetWindowIcon = proxy.SetWindowIcon;
/// Set icon for window (multiple images, RGBA 32bit)
const SetWindowIcons = proxy.SetWindowIcons;
/// Set title for window
const SetWindowTitle = proxy.SetWindowTitle;
/// Set window position on screen
void SetWindowPosition(int x, int y) => raw.SetWindowPosition(x, y);
/// Set monitor for the current window
void SetWindowMonitor(int monitor) => raw.SetWindowMonitor(monitor);
/// Set window minimum dimensions (for FLAG_WINDOW_RESIZABLE)
void SetWindowMinSize(int width, int height) => raw.SetWindowMinSize(width, height);
/// Set window maximum dimensions (for FLAG_WINDOW_RESIZABLE)
void SetWindowMaxSize(int width, int height) => raw.SetWindowMaxSize(width, height);
/// Set window dimensions
void SetWindowSize(int width, int height) => raw.SetWindowSize(width, height);
/// Set window opacity [0.0f..1.0f]
void SetWindowOpacity(double opacity) => raw.SetWindowOpacity(opacity);
/// Set window focused
void SetWindowFocused() => raw.SetWindowFocused();
/// Get native window handle
const GetWindowHandle = proxy.GetWindowHandle;
/// Get current screen width
int GetScreenWidth() => raw.GetScreenWidth();
/// Get current screen height
int GetScreenHeight() => raw.GetScreenHeight();
/// Get current render width (it considers HiDPI)
int GetRenderWidth() => raw.GetRenderWidth();
/// Get current render height (it considers HiDPI)
int GetRenderHeight() => raw.GetRenderHeight();
/// Get number of connected monitors
int GetMonitorCount() => raw.GetMonitorCount();
/// Get current monitor where window is placed
int GetCurrentMonitor() => raw.GetCurrentMonitor();
/// Get specified monitor position
const GetMonitorPosition = proxy.GetMonitorPosition;
/// Get specified monitor width (current video mode used by monitor)
int GetMonitorWidth(int monitor) => raw.GetMonitorWidth(monitor);
/// Get specified monitor height (current video mode used by monitor)
int GetMonitorHeight(int monitor) => raw.GetMonitorHeight(monitor);
/// Get specified monitor physical width in millimetres
int GetMonitorPhysicalWidth(int monitor) => raw.GetMonitorPhysicalWidth(monitor);
/// Get specified monitor physical height in millimetres
int GetMonitorPhysicalHeight(int monitor) => raw.GetMonitorPhysicalHeight(monitor);
/// Get specified monitor refresh rate
int GetMonitorRefreshRate(int monitor) => raw.GetMonitorRefreshRate(monitor);
/// Get window position XY on monitor
const GetWindowPosition = proxy.GetWindowPosition;
/// Get window scale DPI factor
const GetWindowScaleDPI = proxy.GetWindowScaleDPI;
/// Get the human-readable, UTF-8 encoded name of the specified monitor
const GetMonitorName = proxy.GetMonitorName;
/// Set clipboard text content
const SetClipboardText = proxy.SetClipboardText;
/// Get clipboard text content
const GetClipboardText = proxy.GetClipboardText;
/// Get clipboard image content
const GetClipboardImage = proxy.GetClipboardImage;
/// Enable waiting for events on EndDrawing(), no automatic event polling
void EnableEventWaiting() => raw.EnableEventWaiting();
/// Disable waiting for events on EndDrawing(), automatic events polling
void DisableEventWaiting() => raw.DisableEventWaiting();

// Cursor-related functions
/// Shows cursor
void ShowCursor() => raw.ShowCursor();
/// Hides cursor
void HideCursor() => raw.HideCursor();
/// Check if cursor is not visible
bool IsCursorHidden() => raw.IsCursorHidden();
/// Enables cursor (unlock cursor)
void EnableCursor() => raw.EnableCursor();
/// Disables cursor (lock cursor)
void DisableCursor() => raw.DisableCursor();
/// Check if cursor is on the screen
bool IsCursorOnScreen() => raw.IsCursorOnScreen();

// Drawing-related functions
/// Set background color (framebuffer clear color)
const ClearBackground = proxy.ClearBackground;
/// Setup canvas (framebuffer) to start drawing
void BeginDrawing() => raw.BeginDrawing();
/// End canvas drawing and swap buffers (double buffering)
void EndDrawing() => raw.EndDrawing();
/// Begin 2D mode with custom camera (2D)
const BeginMode2D = proxy.BeginMode2D;
/// Ends 2D mode with custom camera
void EndMode2D() => raw.EndMode2D();
/// Begin 3D mode with custom camera (3D)
const BeginMode3D = proxy.BeginMode3D;
/// Ends 3D mode and returns to default 2D orthographic mode
void EndMode3D() => raw.EndMode3D();
/// Begin drawing to render texture
const BeginTextureMode = proxy.BeginTextureMode;
/// Ends drawing to render texture
void EndTextureMode() => raw.EndTextureMode();
/// Begin custom shader drawing
const BeginShaderMode = proxy.BeginShaderMode;
/// End custom shader drawing (use default shader)
void EndShaderMode() => raw.EndShaderMode();
/// Begin blending mode (alpha, additive, multiplied, subtract, custom)
const BeginBlendMode = proxy.BeginBlendMode;
/// End blending mode (reset to default: alpha blending)
void EndBlendMode() => raw.EndBlendMode();
/// Begin scissor mode (define screen area for following drawing)
void BeginScissorMode(int x, int y, int width, int height) => raw.BeginScissorMode(x, y, width, height);
/// End scissor mode
void EndScissorMode() => raw.EndScissorMode();
/// Begin stereo rendering (requires VR simulator)
const BeginVrStereoMode = proxy.BeginVrStereoMode;
/// End stereo rendering (requires VR simulator)
void EndVrStereoMode() => raw.EndVrStereoMode();

// VR stereo config functions for VR simulator
/// Load VR stereo config for VR simulator device parameters
const LoadVrStereoConfig = proxy.LoadVrStereoConfig;
/// Unload VR stereo config
const UnloadVrStereoConfig = proxy.UnloadVrStereoConfig;

// Shader management functions
// NOTE: Shader functionality is not available on OpenGL 1.1
/// Load shader from files and bind default locations
const LoadShader = proxy.LoadShader;
/// Load shader from code strings and bind default locations
const LoadShaderFromMemory = proxy.LoadShaderFromMemory;
/// Check if a shader is valid (loaded on GPU)
const IsShaderValid = proxy.IsShaderValid;
/// Get shader uniform location
const GetShaderLocation = proxy.GetShaderLocation;
/// Get shader attribute location
const GetShaderLocationAttrib = proxy.GetShaderLocationAttrib;
/// Set shader uniform value
const SetShaderValue = proxy.SetShaderValue;
/// Set shader uniform value vector
const SetShaderValueV = proxy.SetShaderValueV;
/// Set shader uniform value (matrix 4x4)
const SetShaderValueMatrix = proxy.SetShaderValueMatrix;
/// Set shader uniform value and bind the texture (sampler2d)
const SetShaderValueTexture = proxy.SetShaderValueTexture;
/// Unload shader from GPU memory (VRAM)
const UnloadShader = proxy.UnloadShader;

// Screen-space-related functions
/// Get a ray trace from screen position (i.e mouse)
const GetScreenToWorldRay = proxy.GetScreenToWorldRay;
/// Get a ray trace from screen position (i.e mouse) in a viewport
const GetScreenToWorldRayEx = proxy.GetScreenToWorldRayEx;
/// Get the screen space position for a 3d world space position
const GetWorldToScreen = proxy.GetWorldToScreen;
/// Get size position for a 3d world space position
const GetWorldToScreenEx = proxy.GetWorldToScreenEx;
/// Get the screen space position for a 2d camera world space position
const GetWorldToScreen2D = proxy.GetWorldToScreen2D;
/// Get the world space position for a 2d camera screen space position
const GetScreenToWorld2D = proxy.GetScreenToWorld2D;
/// Get camera transform matrix (view matrix)
const GetCameraMatrix = proxy.GetCameraMatrix;
/// Get camera 2d transform matrix
const GetCameraMatrix2D = proxy.GetCameraMatrix2D;

// Timing-related functions
/// Set target FPS (maximum)
void SetTargetFPS(int fps) => raw.SetTargetFPS(fps);
/// Get time in seconds for last frame drawn (delta time)
double GetFrameTime() => raw.GetFrameTime();
/// Get elapsed time in seconds since InitWindow()
double GetTime() => raw.GetTime();
/// Get current FPS
int GetFPS() => raw.GetFPS();

// Custom frame control functions
// NOTE: Those functions are intended for advanced users that want full control over the frame processing
// By default EndDrawing() does this job: draws everything + SwapScreenBuffer() + manage frame timing + PollInputEvents()
// To avoid that behaviour and control frame processes manually, enable in config.h: SUPPORT_CUSTOM_FRAME_CONTROL
/// Swap back buffer with front buffer (screen drawing)
void SwapScreenBuffer() => raw.SwapScreenBuffer();
/// Register all input events
void PollInputEvents() => raw.PollInputEvents();
/// Wait for some time (halt program execution)
void WaitTime(double seconds) => raw.WaitTime(seconds);

// Random values generation functions
/// Set the seed for the random number generator
void SetRandomSeed(int seed) => raw.SetRandomSeed(seed);
/// Get a random value between min and max (both included)
int GetRandomValue(int min, int max) => raw.GetRandomValue(min, max);
/// Load random values sequence, no values repeated
const LoadRandomSequence = proxy.LoadRandomSequence;
/// Unload random values sequence
const UnloadRandomSequence = proxy.UnloadRandomSequence;

// Misc. functions
/// Takes a screenshot of current screen (filename extension defines format)
const TakeScreenshot = proxy.TakeScreenshot;
/// Setup init configuration flags (view FLAGS)
const SetConfigFlags = proxy.SetConfigFlags;
/// Open URL with default system browser (if available)
const OpenURL = proxy.OpenURL;

// Logging system
/// Set the current threshold (minimum) log level
const SetTraceLogLevel = proxy.SetTraceLogLevel;
/// Show trace log messages (LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR...)
const TraceLog = proxy.TraceLog;
/// Set custom trace log
const SetTraceLogCallback = proxy.SetTraceLogCallback;

// Memory management, using internal allocators
/// Internal memory allocator
const MemAlloc = proxy.MemAlloc;
/// Internal memory reallocator
const MemRealloc = proxy.MemRealloc;
/// Internal memory free
const MemFree = proxy.MemFree;

// File system management functions
/// Load file data as byte array (read)
const LoadFileData = proxy.LoadFileData;
/// Unload file data allocated by LoadFileData()
const UnloadFileData = proxy.UnloadFileData;
/// Save data to file from byte array (write), returns true on success
const SaveFileData = proxy.SaveFileData;
/// Export data to code (.h), returns true on success
const ExportDataAsCode = proxy.ExportDataAsCode;
/// Load text data from file (read), returns a '\0' terminated string
const LoadFileText = proxy.LoadFileText;
/// Unload file text data allocated by LoadFileText()
const UnloadFileText = proxy.UnloadFileText;
/// Save text data to file (write), string must be '\0' terminated, returns true on success
const SaveFileText = proxy.SaveFileText;

// File access custom callbacks
// WARNING: Callbacks setup is intended for advanced users
/// Set custom file binary data loader
const SetLoadFileDataCallback = proxy.SetLoadFileDataCallback;
/// Set custom file binary data saver
const SetSaveFileDataCallback = proxy.SetSaveFileDataCallback;
/// Set custom file text data loader
const SetLoadFileTextCallback = proxy.SetLoadFileTextCallback;
/// Set custom file text data saver
const SetSaveFileTextCallback = proxy.SetSaveFileTextCallback;

/// Rename file (if exists)
const FileRename = proxy.FileRename;
/// Remove file (if exists)
const FileRemove = proxy.FileRemove;
/// Copy file from one path to another, dstPath created if it doesn't exist
const FileCopy = proxy.FileCopy;
/// Move file from one directory to another, dstPath created if it doesn't exist
const FileMove = proxy.FileMove;
/// Replace text in an existing file
const FileTextReplace = proxy.FileTextReplace;
/// Find text in existing file
const FileTextFindIndex = proxy.FileTextFindIndex;
/// Check if file exists
const FileExists = proxy.FileExists;
/// Check if a directory path exists
const DirectoryExists = proxy.DirectoryExists;
/// Check file extension (recommended include point: .png, .wav)
const IsFileExtension = proxy.IsFileExtension;
/// Get file length in bytes (NOTE: GetFileSize() conflicts with windows.h)
const GetFileLength = proxy.GetFileLength;
/// Get file modification time (last write time)
const GetFileModTime = proxy.GetFileModTime;
/// Get pointer to extension for a filename string (includes dot: '.png')
const GetFileExtension = proxy.GetFileExtension;
/// Get pointer to filename for a path string
const GetFileName = proxy.GetFileName;
/// Get filename string without extension (uses static string)
const GetFileNameWithoutExt = proxy.GetFileNameWithoutExt;
/// Get full path for a given fileName with path (uses static string)
const GetDirectoryPath = proxy.GetDirectoryPath;
/// Get previous directory path for a given path (uses static string)
const GetPrevDirectoryPath = proxy.GetPrevDirectoryPath;
/// Get current working directory (uses static string)
const GetWorkingDirectory = proxy.GetWorkingDirectory;
/// Get the directory of the running application (uses static string)
const GetApplicationDirectory = proxy.GetApplicationDirectory;
/// Create directories (including full path requested), returns 0 on success
const MakeDirectory = proxy.MakeDirectory;
/// Change working directory, return true on success
const ChangeDirectory = proxy.ChangeDirectory;
/// Check if a given path is a file or a directory
const IsPathFile = proxy.IsPathFile;
/// Check if fileName is valid for the platform/OS
const IsFileNameValid = proxy.IsFileNameValid;
/// Load directory filepaths, files and directories, no subdirs scan
const LoadDirectoryFiles = proxy.LoadDirectoryFiles;
/// Load directory filepaths with extension filtering and subdir scan; some filters available: "*.*", "FILES*", "DIRS*"
const LoadDirectoryFilesEx = proxy.LoadDirectoryFilesEx;
/// Unload filepaths
const UnloadDirectoryFiles = proxy.UnloadDirectoryFiles;
/// Check if a file has been dropped into window
bool IsFileDropped() => raw.IsFileDropped();
/// Load dropped filepaths
const LoadDroppedFiles = proxy.LoadDroppedFiles;
/// Unload dropped filepaths
const UnloadDroppedFiles = proxy.UnloadDroppedFiles;
/// Get the file count in a directory
const GetDirectoryFileCount = proxy.GetDirectoryFileCount;
/// Get the file count in a directory with extension filtering and recursive directory scan. Use 'DIR' in the filter string to include directories in the result
const GetDirectoryFileCountEx = proxy.GetDirectoryFileCountEx;

// Compression/Encoding functionality
/// Compress data (DEFLATE algorithm), memory must be MemFree()
const CompressData = proxy.CompressData;
/// Decompress data (DEFLATE algorithm), memory must be MemFree()
const DecompressData = proxy.DecompressData;
/// Encode data to Base64 string (includes NULL terminator), memory must be MemFree()
const EncodeDataBase64 = proxy.EncodeDataBase64;
/// Decode Base64 string (expected NULL terminated), memory must be MemFree()
const DecodeDataBase64 = proxy.DecodeDataBase64;
/// Compute CRC32 hash code
const ComputeCRC32 = proxy.ComputeCRC32;
/// Compute MD5 hash code, returns static int[4] (16 bytes)
const ComputeMD5 = proxy.ComputeMD5;
/// Compute SHA1 hash code, returns static int[5] (20 bytes)
const ComputeSHA1 = proxy.ComputeSHA1;
/// Compute SHA256 hash code, returns static int[8] (32 bytes)
const ComputeSHA256 = proxy.ComputeSHA256;

// Automation events functionality
/// Load automation events list from file, NULL for empty list, capacity = MAX_AUTOMATION_EVENTS
const LoadAutomationEventList = proxy.LoadAutomationEventList;
/// Unload automation events list from file
const UnloadAutomationEventList = proxy.UnloadAutomationEventList;
/// Export automation events list as text file
const ExportAutomationEventList = proxy.ExportAutomationEventList;
/// Set automation event list to record to
const SetAutomationEventList = proxy.SetAutomationEventList;
/// Set automation event internal base frame to start recording
void SetAutomationEventBaseFrame(int frame) => raw.SetAutomationEventBaseFrame(frame);
/// Start recording automation events (AutomationEventList must be set)
void StartAutomationEventRecording() => raw.StartAutomationEventRecording();
/// Stop recording automation events
void StopAutomationEventRecording() => raw.StopAutomationEventRecording();
/// Play a recorded automation event
const PlayAutomationEvent = proxy.PlayAutomationEvent;

//------------------------------------------------------------------------------------
// Input Handling Functions (Module: core)
//------------------------------------------------------------------------------------

// Input-related functions: keyboard
/// Check if a key has been pressed once
const IsKeyPressed = proxy.IsKeyPressed;
/// Check if a key has been pressed again
const IsKeyPressedRepeat = proxy.IsKeyPressedRepeat;
/// Check if a key is being pressed
const IsKeyDown = proxy.IsKeyDown;
/// Check if a key has been released once
const IsKeyReleased = proxy.IsKeyReleased;
/// Check if a key is NOT being pressed
const IsKeyUp = proxy.IsKeyUp;
/// Get key pressed (keycode), call it multiple times for keys queued, returns 0 when the queue is empty
const GetKeyPressed = proxy.GetKeyPressed;
/// Get char pressed (unicode), call it multiple times for chars queued, returns 0 when the queue is empty
int GetCharPressed() => raw.GetCharPressed();
/// Get name of a QWERTY key on the current keyboard layout (eg returns string 'q' for KEY_A on an AZERTY keyboard)
const GetKeyName = proxy.GetKeyName;
/// Set a custom key to exit program (default is ESC)
const SetExitKey = proxy.SetExitKey;

// Input-related functions: gamepads
/// Check if a gamepad is available
bool IsGamepadAvailable(int gamepad) => raw.IsGamepadAvailable(gamepad);
/// Get gamepad internal name id
const GetGamepadName = proxy.GetGamepadName;
/// Check if a gamepad button has been pressed once
const IsGamepadButtonPressed = proxy.IsGamepadButtonPressed;
/// Check if a gamepad button is being pressed
const IsGamepadButtonDown = proxy.IsGamepadButtonDown;
/// Check if a gamepad button has been released once
const IsGamepadButtonReleased = proxy.IsGamepadButtonReleased;
/// Check if a gamepad button is NOT being pressed
const IsGamepadButtonUp = proxy.IsGamepadButtonUp;
/// Get the last gamepad button pressed
const GetGamepadButtonPressed = proxy.GetGamepadButtonPressed;
/// Get axis count for a gamepad
int GetGamepadAxisCount(int gamepad) => raw.GetGamepadAxisCount(gamepad);
/// Get movement value for a gamepad axis
const GetGamepadAxisMovement = proxy.GetGamepadAxisMovement;
/// Set internal gamepad mappings (SDL_GameControllerDB)
const SetGamepadMappings = proxy.SetGamepadMappings;
/// Set gamepad vibration for both motors (duration in seconds)
void SetGamepadVibration(int gamepad, double leftMotor, double rightMotor, double duration) => raw.SetGamepadVibration(gamepad, leftMotor, rightMotor, duration);

// Input-related functions: mouse
/// Check if a mouse button has been pressed once
const IsMouseButtonPressed = proxy.IsMouseButtonPressed;
/// Check if a mouse button is being pressed
const IsMouseButtonDown = proxy.IsMouseButtonDown;
/// Check if a mouse button has been released once
const IsMouseButtonReleased = proxy.IsMouseButtonReleased;
/// Check if a mouse button is NOT being pressed
const IsMouseButtonUp = proxy.IsMouseButtonUp;
/// Get mouse position X
int GetMouseX() => raw.GetMouseX();
/// Get mouse position Y
int GetMouseY() => raw.GetMouseY();
/// Get mouse position XY
const GetMousePosition = proxy.GetMousePosition;
/// Get mouse delta between frames
const GetMouseDelta = proxy.GetMouseDelta;
/// Set mouse position XY
void SetMousePosition(int x, int y) => raw.SetMousePosition(x, y);
/// Set mouse offset
void SetMouseOffset(int offsetX, int offsetY) => raw.SetMouseOffset(offsetX, offsetY);
/// Set mouse scaling
void SetMouseScale(double scaleX, double scaleY) => raw.SetMouseScale(scaleX, scaleY);
/// Get mouse wheel movement for X or Y, whichever is larger
double GetMouseWheelMove() => raw.GetMouseWheelMove();
/// Get mouse wheel movement for both X and Y
const GetMouseWheelMoveV = proxy.GetMouseWheelMoveV;
/// Set mouse cursor
const SetMouseCursor = proxy.SetMouseCursor;

// Input-related functions: touch
/// Get touch position X for touch point 0 (relative to screen size)
int GetTouchX() => raw.GetTouchX();
/// Get touch position Y for touch point 0 (relative to screen size)
int GetTouchY() => raw.GetTouchY();
/// Get touch position XY for a touch point index (relative to screen size)
const GetTouchPosition = proxy.GetTouchPosition;
/// Get touch point identifier for given index
int GetTouchPointId(int index) => raw.GetTouchPointId(index);
/// Get number of touch points
int GetTouchPointCount() => raw.GetTouchPointCount();

//------------------------------------------------------------------------------------
// Gestures and Touch Handling Functions (Module: rgestures)
//------------------------------------------------------------------------------------
/// Enable a set of gestures using flags
const SetGesturesEnabled = proxy.SetGesturesEnabled;
/// Check if a gesture have been detected
const IsGestureDetected = proxy.IsGestureDetected;
/// Get latest detected gesture
const GetGestureDetected = proxy.GetGestureDetected;
/// Get gesture hold time in seconds
double GetGestureHoldDuration() => raw.GetGestureHoldDuration();
/// Get gesture drag vector
const GetGestureDragVector = proxy.GetGestureDragVector;
/// Get gesture drag angle
double GetGestureDragAngle() => raw.GetGestureDragAngle();
/// Get gesture pinch delta
const GetGesturePinchVector = proxy.GetGesturePinchVector;
/// Get gesture pinch angle
double GetGesturePinchAngle() => raw.GetGesturePinchAngle();

//------------------------------------------------------------------------------------
// Camera System Functions (Module: rcamera)
//------------------------------------------------------------------------------------
/// Update camera position for selected mode
const UpdateCamera = proxy.UpdateCamera;
/// Update camera movement/rotation
const UpdateCameraPro = proxy.UpdateCameraPro;


