// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'shapes_proxy.dart' as proxy;
import 'structs.dart';

// NOTE: It can be useful when using basic shapes and one single font,
// defining a font char white rectangle would allow drawing everything in a single draw call
/// Set texture and rectangle to be used on shapes drawing
const SetShapesTexture = proxy.SetShapesTexture;
/// Get texture that is used for shapes drawing
const GetShapesTexture = proxy.GetShapesTexture;
/// Get texture source rectangle that is used for shapes drawing
const GetShapesTextureRectangle = proxy.GetShapesTextureRectangle;

// Basic shapes drawing functions
/// Draw a pixel using geometry [Can be slow, use with care]
const DrawPixel = proxy.DrawPixel;
/// Draw a pixel using geometry (Vector version) [Can be slow, use with care]
const DrawPixelV = proxy.DrawPixelV;
/// Draw a line
const DrawLine = proxy.DrawLine;
/// Draw a line (using gl lines)
const DrawLineV = proxy.DrawLineV;
/// Draw a line (using triangles/quads)
const DrawLineEx = proxy.DrawLineEx;
/// Draw lines sequence (using gl lines)
const DrawLineStrip = proxy.DrawLineStrip;
/// Draw line segment cubic-bezier in-out interpolation
const DrawLineBezier = proxy.DrawLineBezier;
/// Draw a dashed line
const DrawLineDashed = proxy.DrawLineDashed;
/// Draw a color-filled circle
const DrawCircle = proxy.DrawCircle;
/// Draw a color-filled circle (Vector version)
const DrawCircleV = proxy.DrawCircleV;
/// Draw a gradient-filled circle
const DrawCircleGradient = proxy.DrawCircleGradient;
/// Draw a piece of a circle
const DrawCircleSector = proxy.DrawCircleSector;
/// Draw circle sector outline
const DrawCircleSectorLines = proxy.DrawCircleSectorLines;
/// Draw circle outline
const DrawCircleLines = proxy.DrawCircleLines;
/// Draw circle outline (Vector version)
const DrawCircleLinesV = proxy.DrawCircleLinesV;
/// Draw ellipse
const DrawEllipse = proxy.DrawEllipse;
/// Draw ellipse (Vector version)
const DrawEllipseV = proxy.DrawEllipseV;
/// Draw ellipse outline
const DrawEllipseLines = proxy.DrawEllipseLines;
/// Draw ellipse outline (Vector version)
const DrawEllipseLinesV = proxy.DrawEllipseLinesV;
/// Draw ring
const DrawRing = proxy.DrawRing;
/// Draw ring outline
const DrawRingLines = proxy.DrawRingLines;
/// Draw a color-filled rectangle
const DrawRectangle = proxy.DrawRectangle;
/// Draw a color-filled rectangle (Vector version)
const DrawRectangleV = proxy.DrawRectangleV;
/// Draw a color-filled rectangle
const DrawRectangleRec = proxy.DrawRectangleRec;
/// Draw a color-filled rectangle with pro parameters
const DrawRectanglePro = proxy.DrawRectanglePro;
/// Draw a vertical-gradient-filled rectangle
const DrawRectangleGradientV = proxy.DrawRectangleGradientV;
/// Draw a horizontal-gradient-filled rectangle
const DrawRectangleGradientH = proxy.DrawRectangleGradientH;
/// Draw a gradient-filled rectangle with custom vertex colors
const DrawRectangleGradientEx = proxy.DrawRectangleGradientEx;
/// Draw rectangle outline
const DrawRectangleLines = proxy.DrawRectangleLines;
/// Draw rectangle outline with extended parameters
const DrawRectangleLinesEx = proxy.DrawRectangleLinesEx;
/// Draw rectangle with rounded edges
const DrawRectangleRounded = proxy.DrawRectangleRounded;
/// Draw rectangle lines with rounded edges
const DrawRectangleRoundedLines = proxy.DrawRectangleRoundedLines;
/// Draw rectangle with rounded edges outline
const DrawRectangleRoundedLinesEx = proxy.DrawRectangleRoundedLinesEx;
/// Draw a color-filled triangle (vertex in counter-clockwise order!)
const DrawTriangle = proxy.DrawTriangle;
/// Draw triangle outline (vertex in counter-clockwise order!)
const DrawTriangleLines = proxy.DrawTriangleLines;
/// Draw a triangle fan defined by points (first vertex is the center)
const DrawTriangleFan = proxy.DrawTriangleFan;
/// Draw a triangle strip defined by points
const DrawTriangleStrip = proxy.DrawTriangleStrip;
/// Draw a regular polygon (Vector version)
const DrawPoly = proxy.DrawPoly;
/// Draw a polygon outline of n sides
const DrawPolyLines = proxy.DrawPolyLines;
/// Draw a polygon outline of n sides with extended parameters
const DrawPolyLinesEx = proxy.DrawPolyLinesEx;

// Splines drawing functions
/// Draw spline: Linear, minimum 2 points
const DrawSplineLinear = proxy.DrawSplineLinear;
/// Draw spline: B-Spline, minimum 4 points
const DrawSplineBasis = proxy.DrawSplineBasis;
/// Draw spline: Catmull-Rom, minimum 4 points
const DrawSplineCatmullRom = proxy.DrawSplineCatmullRom;
/// Draw spline: Quadratic Bezier, minimum 3 points (1 control point): [p1, c2, p3, c4...]
const DrawSplineBezierQuadratic = proxy.DrawSplineBezierQuadratic;
/// Draw spline: Cubic Bezier, minimum 4 points (2 control points): [p1, c2, c3, p4, c5, c6...]
const DrawSplineBezierCubic = proxy.DrawSplineBezierCubic;
/// Draw spline segment: Linear, 2 points
const DrawSplineSegmentLinear = proxy.DrawSplineSegmentLinear;
/// Draw spline segment: B-Spline, 4 points
const DrawSplineSegmentBasis = proxy.DrawSplineSegmentBasis;
/// Draw spline segment: Catmull-Rom, 4 points
const DrawSplineSegmentCatmullRom = proxy.DrawSplineSegmentCatmullRom;
/// Draw spline segment: Quadratic Bezier, 2 points, 1 control point
const DrawSplineSegmentBezierQuadratic = proxy.DrawSplineSegmentBezierQuadratic;
/// Draw spline segment: Cubic Bezier, 2 points, 2 control points
const DrawSplineSegmentBezierCubic = proxy.DrawSplineSegmentBezierCubic;

// Spline segment point evaluation functions, for a given t [0.0f .. 1.0f]
/// Get (evaluate) spline point: Linear
const GetSplinePointLinear = proxy.GetSplinePointLinear;
/// Get (evaluate) spline point: B-Spline
const GetSplinePointBasis = proxy.GetSplinePointBasis;
/// Get (evaluate) spline point: Catmull-Rom
const GetSplinePointCatmullRom = proxy.GetSplinePointCatmullRom;
/// Get (evaluate) spline point: Quadratic Bezier
const GetSplinePointBezierQuad = proxy.GetSplinePointBezierQuad;
/// Get (evaluate) spline point: Cubic Bezier
const GetSplinePointBezierCubic = proxy.GetSplinePointBezierCubic;

// Basic shapes collision detection functions
/// Check collision between two rectangles
const CheckCollisionRecs = proxy.CheckCollisionRecs;
/// Check collision between two circles
const CheckCollisionCircles = proxy.CheckCollisionCircles;
/// Check collision between circle and rectangle
const CheckCollisionCircleRec = proxy.CheckCollisionCircleRec;
/// Check if circle collides with a line created betweeen two points [p1] and [p2]
const CheckCollisionCircleLine = proxy.CheckCollisionCircleLine;
/// Check if point is inside rectangle
const CheckCollisionPointRec = proxy.CheckCollisionPointRec;
/// Check if point is inside circle
const CheckCollisionPointCircle = proxy.CheckCollisionPointCircle;
/// Check if point is inside a triangle
const CheckCollisionPointTriangle = proxy.CheckCollisionPointTriangle;
/// Check if point belongs to line created between two points [p1] and [p2] with defined margin in pixels [threshold]
const CheckCollisionPointLine = proxy.CheckCollisionPointLine;
/// Check if point is within a polygon described by array of vertices
const CheckCollisionPointPoly = proxy.CheckCollisionPointPoly;
/// Check the collision between two lines defined by two points each, returns collision point by reference
const CheckCollisionLines = proxy.CheckCollisionLines;
/// Get collision rectangle for two rectangles collision
const GetCollisionRec = proxy.GetCollisionRec;


