// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'textures_proxy.dart' as proxy;
import 'dart:typed_data';
import 'raylib_const.dart';
import 'structs.dart';

// Image loading functions
// NOTE: These functions do not require GPU access
/// Load image from file into CPU memory (RAM)
const LoadImage = proxy.LoadImage;
/// Load image from RAW file data
const LoadImageRaw = proxy.LoadImageRaw;
/// Load image sequence from file (frames appended to image.data)
const LoadImageAnim = proxy.LoadImageAnim;
/// Load image sequence from memory buffer
const LoadImageAnimFromMemory = proxy.LoadImageAnimFromMemory;
/// Load image from memory buffer, fileType refers to extension: i.e. '.png'
const LoadImageFromMemory = proxy.LoadImageFromMemory;
/// Load image from GPU texture data
const LoadImageFromTexture = proxy.LoadImageFromTexture;
/// Load image from screen buffer and (screenshot)
const LoadImageFromScreen = proxy.LoadImageFromScreen;
/// Check if an image is valid (data and parameters)
const IsImageValid = proxy.IsImageValid;
/// Unload image from CPU memory (RAM)
const UnloadImage = proxy.UnloadImage;
/// Export image data to file, returns true on success
const ExportImage = proxy.ExportImage;
/// Export image to memory buffer, memory must be MemFree()
const ExportImageToMemory = proxy.ExportImageToMemory;
/// Export image as code file defining an array of bytes, returns true on success
const ExportImageAsCode = proxy.ExportImageAsCode;

// Image generation functions
/// Generate image: plain color
const GenImageColor = proxy.GenImageColor;
/// Generate image: linear gradient, direction in degrees [0..360], 0=Vertical gradient
const GenImageGradientLinear = proxy.GenImageGradientLinear;
/// Generate image: radial gradient
const GenImageGradientRadial = proxy.GenImageGradientRadial;
/// Generate image: square gradient
const GenImageGradientSquare = proxy.GenImageGradientSquare;
/// Generate image: checked
const GenImageChecked = proxy.GenImageChecked;
/// Generate image: white noise
const GenImageWhiteNoise = proxy.GenImageWhiteNoise;
/// Generate image: perlin noise
const GenImagePerlinNoise = proxy.GenImagePerlinNoise;
/// Generate image: cellular algorithm, bigger tileSize means bigger cells
const GenImageCellular = proxy.GenImageCellular;
/// Generate image: grayscale image from text data
const GenImageText = proxy.GenImageText;

// Image manipulation functions
/// Create an image duplicate (useful for transformations)
const ImageCopy = proxy.ImageCopy;
/// Create an image from another image piece
const ImageFromImage = proxy.ImageFromImage;
/// Create an image from a selected channel of another image (GRAYSCALE)
const ImageFromChannel = proxy.ImageFromChannel;
/// Create an image from text (default font)
const ImageText = proxy.ImageText;
/// Create an image from text (custom sprite font)
const ImageTextEx = proxy.ImageTextEx;
/// Convert image data to desired format
const ImageFormat = proxy.ImageFormat;
/// Convert image to POT (power-of-two)
const ImageToPOT = proxy.ImageToPOT;
/// Crop an image to a defined rectangle
const ImageCrop = proxy.ImageCrop;
/// Crop image depending on alpha value
const ImageAlphaCrop = proxy.ImageAlphaCrop;
/// Clear alpha channel to desired color
const ImageAlphaClear = proxy.ImageAlphaClear;
/// Apply alpha mask to image
const ImageAlphaMask = proxy.ImageAlphaMask;
/// Premultiply alpha channel
const ImageAlphaPremultiply = proxy.ImageAlphaPremultiply;
/// Apply Gaussian blur using a box blur approximation
const ImageBlurGaussian = proxy.ImageBlurGaussian;
/// Apply custom square convolution kernel to image
const ImageKernelConvolution = proxy.ImageKernelConvolution;
/// Resize image (Bicubic scaling algorithm)
const ImageResize = proxy.ImageResize;
/// Resize image (Nearest-Neighbor scaling algorithm)
const ImageResizeNN = proxy.ImageResizeNN;
/// Resize canvas and fill with color
const ImageResizeCanvas = proxy.ImageResizeCanvas;
/// Compute all mipmap levels for a provided image
const ImageMipmaps = proxy.ImageMipmaps;
/// Dither image data to 16bpp or lower (Floyd-Steinberg dithering)
const ImageDither = proxy.ImageDither;
/// Flip image vertically
const ImageFlipVertical = proxy.ImageFlipVertical;
/// Flip image horizontally
const ImageFlipHorizontal = proxy.ImageFlipHorizontal;
/// Rotate image by input angle in degrees (-359 to 359)
const ImageRotate = proxy.ImageRotate;
/// Rotate image clockwise 90deg
const ImageRotateCW = proxy.ImageRotateCW;
/// Rotate image counter-clockwise 90deg
const ImageRotateCCW = proxy.ImageRotateCCW;
/// Modify image color: tint
const ImageColorTint = proxy.ImageColorTint;
/// Modify image color: invert
const ImageColorInvert = proxy.ImageColorInvert;
/// Modify image color: grayscale
const ImageColorGrayscale = proxy.ImageColorGrayscale;
/// Modify image color: contrast (-100 to 100)
const ImageColorContrast = proxy.ImageColorContrast;
/// Modify image color: brightness (-255 to 255)
const ImageColorBrightness = proxy.ImageColorBrightness;
/// Modify image color: replace color
const ImageColorReplace = proxy.ImageColorReplace;
/// Load color data from image as a Color array (RGBA - 32bit)
const LoadImageColors = proxy.LoadImageColors;
/// Load colors palette from image as a Color array (RGBA - 32bit)
const LoadImagePalette = proxy.LoadImagePalette;
/// Unload color data loaded with LoadImageColors()
const UnloadImageColors = proxy.UnloadImageColors;
/// Unload colors palette loaded with LoadImagePalette()
const UnloadImagePalette = proxy.UnloadImagePalette;
/// Get image alpha border rectangle
const GetImageAlphaBorder = proxy.GetImageAlphaBorder;
/// Get image pixel color at (x, y) position
const GetImageColor = proxy.GetImageColor;

// Image drawing functions
// NOTE: Image software-rendering functions (CPU)
/// Clear image background with given color
const ImageClearBackground = proxy.ImageClearBackground;
/// Draw pixel within an image
const ImageDrawPixel = proxy.ImageDrawPixel;
/// Draw pixel within an image (Vector version)
const ImageDrawPixelV = proxy.ImageDrawPixelV;
/// Draw line within an image
const ImageDrawLine = proxy.ImageDrawLine;
/// Draw line within an image (Vector version)
const ImageDrawLineV = proxy.ImageDrawLineV;
/// Draw a line defining thickness within an image
const ImageDrawLineEx = proxy.ImageDrawLineEx;
/// Draw a filled circle within an image
const ImageDrawCircle = proxy.ImageDrawCircle;
/// Draw a filled circle within an image (Vector version)
const ImageDrawCircleV = proxy.ImageDrawCircleV;
/// Draw circle outline within an image
const ImageDrawCircleLines = proxy.ImageDrawCircleLines;
/// Draw circle outline within an image (Vector version)
const ImageDrawCircleLinesV = proxy.ImageDrawCircleLinesV;
/// Draw rectangle within an image
const ImageDrawRectangle = proxy.ImageDrawRectangle;
/// Draw rectangle within an image (Vector version)
const ImageDrawRectangleV = proxy.ImageDrawRectangleV;
/// Draw rectangle within an image
const ImageDrawRectangleRec = proxy.ImageDrawRectangleRec;
/// Draw rectangle lines within an image
const ImageDrawRectangleLines = proxy.ImageDrawRectangleLines;
/// Draw triangle within an image
const ImageDrawTriangle = proxy.ImageDrawTriangle;
/// Draw triangle with interpolated colors within an image
const ImageDrawTriangleEx = proxy.ImageDrawTriangleEx;
/// Draw triangle outline within an image
const ImageDrawTriangleLines = proxy.ImageDrawTriangleLines;
/// Draw a triangle fan defined by points within an image (first vertex is the center)
const ImageDrawTriangleFan = proxy.ImageDrawTriangleFan;
/// Draw a triangle strip defined by points within an image
const ImageDrawTriangleStrip = proxy.ImageDrawTriangleStrip;
/// Draw a source image within a destination image (tint applied to source)
const ImageDraw = proxy.ImageDraw;
/// Draw text (using default font) within an image (destination)
const ImageDrawText = proxy.ImageDrawText;
/// Draw text (custom sprite font) within an image (destination)
const ImageDrawTextEx = proxy.ImageDrawTextEx;

// Texture loading functions
// NOTE: These functions require GPU access
/// Load texture from file into GPU memory (VRAM)
const LoadTexture = proxy.LoadTexture;
/// Load texture from image data
const LoadTextureFromImage = proxy.LoadTextureFromImage;
/// Load cubemap from image, multiple image cubemap layouts supported
const LoadTextureCubemap = proxy.LoadTextureCubemap;
/// Load texture for rendering (framebuffer)
const LoadRenderTexture = proxy.LoadRenderTexture;
/// Check if a texture is valid (loaded in GPU)
const IsTextureValid = proxy.IsTextureValid;
/// Unload texture from GPU memory (VRAM)
const UnloadTexture = proxy.UnloadTexture;
/// Check if a render texture is valid (loaded in GPU)
const IsRenderTextureValid = proxy.IsRenderTextureValid;
/// Unload render texture from GPU memory (VRAM)
const UnloadRenderTexture = proxy.UnloadRenderTexture;
/// Update GPU texture with new data (pixels should be able to fill texture)
const UpdateTexture = proxy.UpdateTexture;
/// Update GPU texture rectangle with new data (pixels and rec should fit in texture)
const UpdateTextureRec = proxy.UpdateTextureRec;

// Texture configuration functions
/// Generate GPU mipmaps for a texture
const GenTextureMipmaps = proxy.GenTextureMipmaps;
/// Set texture scaling filter mode
const SetTextureFilter = proxy.SetTextureFilter;
/// Set texture wrapping mode
const SetTextureWrap = proxy.SetTextureWrap;

// Texture drawing functions
/// Draw a Texture2D
const DrawTexture = proxy.DrawTexture;
/// Draw a Texture2D with position defined as Vector2
const DrawTextureV = proxy.DrawTextureV;
/// Draw a Texture2D with extended parameters
const DrawTextureEx = proxy.DrawTextureEx;
/// Draw a part of a texture defined by a rectangle
const DrawTextureRec = proxy.DrawTextureRec;
/// Draw a part of a texture defined by a rectangle with 'pro' parameters
const DrawTexturePro = proxy.DrawTexturePro;
/// Draws a texture (or part of it) that stretches or shrinks nicely
const DrawTextureNPatch = proxy.DrawTextureNPatch;

// Color/pixel related functions
/// Check if two colors are equal
const ColorIsEqual = proxy.ColorIsEqual;
/// Get color with alpha applied, alpha goes from 0.0f to 1.0f
const Fade = proxy.Fade;
/// Get hexadecimal value for a Color (0xRRGGBBAA)
const ColorToInt = proxy.ColorToInt;
/// Get Color normalized as float [0..1]
const ColorNormalize = proxy.ColorNormalize;
/// Get Color from normalized values [0..1]
const ColorFromNormalized = proxy.ColorFromNormalized;
/// Get HSV values for a Color, hue [0..360], saturation/value [0..1]
const ColorToHSV = proxy.ColorToHSV;
/// Get a Color from HSV values, hue [0..360], saturation/value [0..1]
const ColorFromHSV = proxy.ColorFromHSV;
/// Get color multiplied with another color
const ColorTint = proxy.ColorTint;
/// Get color with brightness correction, brightness factor goes from -1.0f to 1.0f
const ColorBrightness = proxy.ColorBrightness;
/// Get color with contrast correction, contrast values between -1.0f and 1.0f
const ColorContrast = proxy.ColorContrast;
/// Get color with alpha applied, alpha goes from 0.0f to 1.0f
const ColorAlpha = proxy.ColorAlpha;
/// Get src alpha-blended into dst color with tint
const ColorAlphaBlend = proxy.ColorAlphaBlend;
/// Get color lerp interpolation between two colors, factor [0.0f..1.0f]
const ColorLerp = proxy.ColorLerp;
/// Get Color structure from hexadecimal value
const GetColor = proxy.GetColor;
/// Get Color from a source pixel pointer of certain format
const GetPixelColor = proxy.GetPixelColor;
/// Set color formatted into destination pixel pointer
const SetPixelColor = proxy.SetPixelColor;
/// Get pixel data size in bytes for certain format
const GetPixelDataSize = proxy.GetPixelDataSize;


