// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'audio_proxy.dart' as proxy;
import 'dart:typed_data';
import 'structs.dart';

// Audio device management functions
/// Initialize audio device and context
void InitAudioDevice() => raw.InitAudioDevice();
/// Close the audio device and context
void CloseAudioDevice() => raw.CloseAudioDevice();
/// Check if audio device has been initialized successfully
bool IsAudioDeviceReady() => raw.IsAudioDeviceReady();
/// Set master volume (listener)
void SetMasterVolume(double volume) => raw.SetMasterVolume(volume);
/// Get master volume (listener)
double GetMasterVolume() => raw.GetMasterVolume();

// Wave/Sound loading/unloading functions
/// Load wave data from file
const LoadWave = proxy.LoadWave;
/// Load wave from memory buffer, fileType refers to extension: i.e. '.wav'
const LoadWaveFromMemory = proxy.LoadWaveFromMemory;
/// Checks if wave data is valid (data loaded and parameters)
const IsWaveValid = proxy.IsWaveValid;
/// Load sound from file
const LoadSound = proxy.LoadSound;
/// Load sound from wave data
const LoadSoundFromWave = proxy.LoadSoundFromWave;
/// Create a new sound that shares the same sample data as the source sound, does not own the sound data
const LoadSoundAlias = proxy.LoadSoundAlias;
/// Checks if a sound is valid (data loaded and buffers initialized)
const IsSoundValid = proxy.IsSoundValid;
/// Update sound buffer with new data (default data format: 32 bit float, stereo)
const UpdateSound = proxy.UpdateSound;
/// Unload wave data
const UnloadWave = proxy.UnloadWave;
/// Unload sound
const UnloadSound = proxy.UnloadSound;
/// Unload a sound alias (does not deallocate sample data)
const UnloadSoundAlias = proxy.UnloadSoundAlias;
/// Export wave data to file, returns true on success
const ExportWave = proxy.ExportWave;
/// Export wave sample data to code (.h), returns true on success
const ExportWaveAsCode = proxy.ExportWaveAsCode;

// Wave/Sound management functions
/// Play a sound
const PlaySound = proxy.PlaySound;
/// Stop playing a sound
const StopSound = proxy.StopSound;
/// Pause a sound
const PauseSound = proxy.PauseSound;
/// Resume a paused sound
const ResumeSound = proxy.ResumeSound;
/// Check if a sound is currently playing
const IsSoundPlaying = proxy.IsSoundPlaying;
/// Set volume for a sound (1.0 is max level)
const SetSoundVolume = proxy.SetSoundVolume;
/// Set pitch for a sound (1.0 is base level)
const SetSoundPitch = proxy.SetSoundPitch;
/// Set pan for a sound (-1.0 left, 0.0 center, 1.0 right)
const SetSoundPan = proxy.SetSoundPan;
/// Copy a wave to a new wave
const WaveCopy = proxy.WaveCopy;
/// Crop a wave to defined frames range
const WaveCrop = proxy.WaveCrop;
/// Convert wave data to desired format
const WaveFormat = proxy.WaveFormat;
/// Load samples data from wave as a 32bit float data array
const LoadWaveSamples = proxy.LoadWaveSamples;
/// Unload samples data loaded with LoadWaveSamples()
const UnloadWaveSamples = proxy.UnloadWaveSamples;

// Music management functions
/// Load music stream from file
const LoadMusicStream = proxy.LoadMusicStream;
/// Load music stream from data
const LoadMusicStreamFromMemory = proxy.LoadMusicStreamFromMemory;
/// Checks if a music stream is valid (context and buffers initialized)
const IsMusicValid = proxy.IsMusicValid;
/// Unload music stream
const UnloadMusicStream = proxy.UnloadMusicStream;
/// Start music playing
const PlayMusicStream = proxy.PlayMusicStream;
/// Check if music is playing
const IsMusicStreamPlaying = proxy.IsMusicStreamPlaying;
/// Updates buffers for music streaming
const UpdateMusicStream = proxy.UpdateMusicStream;
/// Stop music playing
const StopMusicStream = proxy.StopMusicStream;
/// Pause music playing
const PauseMusicStream = proxy.PauseMusicStream;
/// Resume playing paused music
const ResumeMusicStream = proxy.ResumeMusicStream;
/// Seek music to a position (in seconds)
const SeekMusicStream = proxy.SeekMusicStream;
/// Set volume for music (1.0 is max level)
const SetMusicVolume = proxy.SetMusicVolume;
/// Set pitch for a music (1.0 is base level)
const SetMusicPitch = proxy.SetMusicPitch;
/// Set pan for a music (-1.0 left, 0.0 center, 1.0 right)
const SetMusicPan = proxy.SetMusicPan;
/// Get music time length (in seconds)
const GetMusicTimeLength = proxy.GetMusicTimeLength;
/// Get current music time played (in seconds)
const GetMusicTimePlayed = proxy.GetMusicTimePlayed;

// AudioStream management functions
/// Load audio stream (to stream raw audio pcm data)
const LoadAudioStream = proxy.LoadAudioStream;
/// Checks if an audio stream is valid (buffers initialized)
const IsAudioStreamValid = proxy.IsAudioStreamValid;
/// Unload audio stream and free memory
const UnloadAudioStream = proxy.UnloadAudioStream;
/// Update audio stream buffers with data
const UpdateAudioStream = proxy.UpdateAudioStream;
/// Check if any audio stream buffers requires refill
const IsAudioStreamProcessed = proxy.IsAudioStreamProcessed;
/// Play audio stream
const PlayAudioStream = proxy.PlayAudioStream;
/// Pause audio stream
const PauseAudioStream = proxy.PauseAudioStream;
/// Resume audio stream
const ResumeAudioStream = proxy.ResumeAudioStream;
/// Check if audio stream is playing
const IsAudioStreamPlaying = proxy.IsAudioStreamPlaying;
/// Stop audio stream
const StopAudioStream = proxy.StopAudioStream;
/// Set volume for audio stream (1.0 is max level)
const SetAudioStreamVolume = proxy.SetAudioStreamVolume;
/// Set pitch for audio stream (1.0 is base level)
const SetAudioStreamPitch = proxy.SetAudioStreamPitch;
/// Set pan for audio stream (-1.0 to 1.0 range, 0.0 is centered)
const SetAudioStreamPan = proxy.SetAudioStreamPan;
/// Default size for new audio streams
void SetAudioStreamBufferSizeDefault(int size) => raw.SetAudioStreamBufferSizeDefault(size);
/// Audio thread callback to request new data
const SetAudioStreamCallback = proxy.SetAudioStreamCallback;

/// Attach audio stream processor to stream, receives frames x 2 samples as 'float' (stereo)
const AttachAudioStreamProcessor = proxy.AttachAudioStreamProcessor;
/// Detach audio stream processor from stream
const DetachAudioStreamProcessor = proxy.DetachAudioStreamProcessor;

/// Attach audio stream processor to the entire audio pipeline, receives frames x 2 samples as 'float' (stereo)
const AttachAudioMixedProcessor = proxy.AttachAudioMixedProcessor;
/// Detach audio stream processor from the entire audio pipeline
const DetachAudioMixedProcessor = proxy.DetachAudioMixedProcessor;


