// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'audio_proxy.dart' as proxy;
import 'dart:typed_data';
import 'structs.dart';

// Audio device management functions
/// Initialize audio device and context
void InitAudioDevice() => raw.InitAudioDevice();
/// Close the audio device and context
void CloseAudioDevice() => raw.CloseAudioDevice();
/// Check if audio device has been initialized successfully
bool IsAudioDeviceReady() => raw.IsAudioDeviceReady();
/// Set master volume (listener)
void SetMasterVolume(double volume) => raw.SetMasterVolume(volume);
/// Get master volume (listener)
double GetMasterVolume() => raw.GetMasterVolume();

// Wave/Sound loading/unloading functions
/// Load wave data from file
Wave LoadWave(String fileName) => raw.LoadWave(fileName);
/// Load wave from memory buffer, fileType refers to extension: i.e. '.wav'
Wave LoadWaveFromMemory(String fileType, Uint8List fileData) => proxy.LoadWaveFromMemory(fileType, fileData);
/// Checks if wave data is valid (data loaded and parameters)
bool IsWaveValid(Wave wave) => raw.IsWaveValid(wave);
/// Load sound from file
Sound LoadSound(String fileName) => raw.LoadSound(fileName);
/// Load sound from wave data
Sound LoadSoundFromWave(Wave wave) => raw.LoadSoundFromWave(wave);
/// Create a new sound that shares the same sample data as the source sound, does not own the sound data
Sound LoadSoundAlias(Sound source) => raw.LoadSoundAlias(source);
/// Checks if a sound is valid (data loaded and buffers initialized)
bool IsSoundValid(Sound sound) => raw.IsSoundValid(sound);
/// Update sound buffer with new data (default data format: 32 bit float, stereo)
void UpdateSound(Sound sound, Uint8List data, int sampleCount) => proxy.UpdateSound(sound, data, sampleCount);
/// Unload wave data
void UnloadWave(Wave wave) => raw.UnloadWave(wave);
/// Unload sound
void UnloadSound(Sound sound) => raw.UnloadSound(sound);
/// Unload a sound alias (does not deallocate sample data)
void UnloadSoundAlias(Sound alias) => raw.UnloadSoundAlias(alias);
/// Export wave data to file, returns true on success
bool ExportWave(Wave wave, String fileName) => raw.ExportWave(wave, fileName);
/// Export wave sample data to code (.h), returns true on success
bool ExportWaveAsCode(Wave wave, String fileName) => raw.ExportWaveAsCode(wave, fileName);

// Wave/Sound management functions
/// Play a sound
void PlaySound(Sound sound) => raw.PlaySound(sound);
/// Stop playing a sound
void StopSound(Sound sound) => raw.StopSound(sound);
/// Pause a sound
void PauseSound(Sound sound) => raw.PauseSound(sound);
/// Resume a paused sound
void ResumeSound(Sound sound) => raw.ResumeSound(sound);
/// Check if a sound is currently playing
bool IsSoundPlaying(Sound sound) => raw.IsSoundPlaying(sound);
/// Set volume for a sound (1.0 is max level)
void SetSoundVolume(Sound sound, double volume) => raw.SetSoundVolume(sound, volume);
/// Set pitch for a sound (1.0 is base level)
void SetSoundPitch(Sound sound, double pitch) => raw.SetSoundPitch(sound, pitch);
/// Set pan for a sound (-1.0 left, 0.0 center, 1.0 right)
void SetSoundPan(Sound sound, double pan) => raw.SetSoundPan(sound, pan);
/// Copy a wave to a new wave
Wave WaveCopy(Wave wave) => raw.WaveCopy(wave);
/// Crop a wave to defined frames range
void WaveCrop(Wave wave, int initFrame, int finalFrame) => proxy.WaveCrop(wave, initFrame, finalFrame);
/// Convert wave data to desired format
void WaveFormat(Wave wave, int sampleRate, int sampleSize, int channels) => proxy.WaveFormat(wave, sampleRate, sampleSize, channels);
/// Load samples data from wave as a 32bit float data array
Float32List LoadWaveSamples(Wave wave) => proxy.LoadWaveSamples(wave);
/// Unload samples data loaded with LoadWaveSamples()
void UnloadWaveSamples(List<double> samples) => raw.UnloadWaveSamples(samples);

// Music management functions
/// Load music stream from file
Music LoadMusicStream(String fileName) => raw.LoadMusicStream(fileName);
/// Load music stream from data
Music LoadMusicStreamFromMemory(String fileType, Uint8List data) => proxy.LoadMusicStreamFromMemory(fileType, data);
/// Checks if a music stream is valid (context and buffers initialized)
bool IsMusicValid(Music music) => raw.IsMusicValid(music);
/// Unload music stream
void UnloadMusicStream(Music music) => raw.UnloadMusicStream(music);
/// Start music playing
void PlayMusicStream(Music music) => raw.PlayMusicStream(music);
/// Check if music is playing
bool IsMusicStreamPlaying(Music music) => raw.IsMusicStreamPlaying(music);
/// Updates buffers for music streaming
void UpdateMusicStream(Music music) => raw.UpdateMusicStream(music);
/// Stop music playing
void StopMusicStream(Music music) => raw.StopMusicStream(music);
/// Pause music playing
void PauseMusicStream(Music music) => raw.PauseMusicStream(music);
/// Resume playing paused music
void ResumeMusicStream(Music music) => raw.ResumeMusicStream(music);
/// Seek music to a position (in seconds)
void SeekMusicStream(Music music, double position) => raw.SeekMusicStream(music, position);
/// Set volume for music (1.0 is max level)
void SetMusicVolume(Music music, double volume) => raw.SetMusicVolume(music, volume);
/// Set pitch for a music (1.0 is base level)
void SetMusicPitch(Music music, double pitch) => raw.SetMusicPitch(music, pitch);
/// Set pan for a music (-1.0 left, 0.0 center, 1.0 right)
void SetMusicPan(Music music, double pan) => raw.SetMusicPan(music, pan);
/// Get music time length (in seconds)
double GetMusicTimeLength(Music music) => raw.GetMusicTimeLength(music);
/// Get current music time played (in seconds)
double GetMusicTimePlayed(Music music) => raw.GetMusicTimePlayed(music);

// AudioStream management functions
/// Load audio stream (to stream raw audio pcm data)
AudioStream LoadAudioStream(int sampleRate, int sampleSize, int channels) => raw.LoadAudioStream(sampleRate, sampleSize, channels);
/// Checks if an audio stream is valid (buffers initialized)
bool IsAudioStreamValid(AudioStream stream) => raw.IsAudioStreamValid(stream);
/// Unload audio stream and free memory
void UnloadAudioStream(AudioStream stream) => raw.UnloadAudioStream(stream);
/// Update audio stream buffers with data
void UpdateAudioStream(AudioStream stream, Uint8List data, int frameCount) => proxy.UpdateAudioStream(stream, data, frameCount);
/// Check if any audio stream buffers requires refill
bool IsAudioStreamProcessed(AudioStream stream) => raw.IsAudioStreamProcessed(stream);
/// Play audio stream
void PlayAudioStream(AudioStream stream) => raw.PlayAudioStream(stream);
/// Pause audio stream
void PauseAudioStream(AudioStream stream) => raw.PauseAudioStream(stream);
/// Resume audio stream
void ResumeAudioStream(AudioStream stream) => raw.ResumeAudioStream(stream);
/// Check if audio stream is playing
bool IsAudioStreamPlaying(AudioStream stream) => raw.IsAudioStreamPlaying(stream);
/// Stop audio stream
void StopAudioStream(AudioStream stream) => raw.StopAudioStream(stream);
/// Set volume for audio stream (1.0 is max level)
void SetAudioStreamVolume(AudioStream stream, double volume) => raw.SetAudioStreamVolume(stream, volume);
/// Set pitch for audio stream (1.0 is base level)
void SetAudioStreamPitch(AudioStream stream, double pitch) => raw.SetAudioStreamPitch(stream, pitch);
/// Set pan for audio stream (-1.0 to 1.0 range, 0.0 is centered)
void SetAudioStreamPan(AudioStream stream, double pan) => raw.SetAudioStreamPan(stream, pan);
/// Default size for new audio streams
void SetAudioStreamBufferSizeDefault(int size) => raw.SetAudioStreamBufferSizeDefault(size);
/// Audio thread callback to request new data
void SetAudioStreamCallback(AudioStream stream, AudioCallback callback) => raw.SetAudioStreamCallback(stream, callback);

/// Attach audio stream processor to stream, receives frames x 2 samples as 'float' (stereo)
void AttachAudioStreamProcessor(AudioStream stream, AudioCallback processor) => raw.AttachAudioStreamProcessor(stream, processor);
/// Detach audio stream processor from stream
void DetachAudioStreamProcessor(AudioStream stream, AudioCallback processor) => raw.DetachAudioStreamProcessor(stream, processor);

/// Attach audio stream processor to the entire audio pipeline, receives frames x 2 samples as 'float' (stereo)
void AttachAudioMixedProcessor(AudioCallback processor) => raw.AttachAudioMixedProcessor(processor);
/// Detach audio stream processor from the entire audio pipeline
void DetachAudioMixedProcessor(AudioCallback processor) => raw.DetachAudioMixedProcessor(processor);


