// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'core_proxy.dart' as proxy;
import 'raylib_const.dart';
import 'structs.dart';
import 'dart:typed_data';


// Window-related functions
/// Initialize window and OpenGL context
void InitWindow(int width, int height, String title) => proxy.InitWindow(width, height, title);
/// Close window and unload OpenGL context
void CloseWindow() => proxy.CloseWindow();
/// Check if application should close (KEY_ESCAPE pressed or windows close icon clicked)
bool WindowShouldClose() => raw.WindowShouldClose();
/// Check if window has been initialized successfully
bool IsWindowReady() => raw.IsWindowReady();
/// Check if window is currently fullscreen
bool IsWindowFullscreen() => raw.IsWindowFullscreen();
/// Check if window is currently hidden
bool IsWindowHidden() => raw.IsWindowHidden();
/// Check if window is currently minimized
bool IsWindowMinimized() => raw.IsWindowMinimized();
/// Check if window is currently maximized
bool IsWindowMaximized() => raw.IsWindowMaximized();
/// Check if window is currently focused
bool IsWindowFocused() => raw.IsWindowFocused();
/// Check if window has been resized last frame
bool IsWindowResized() => raw.IsWindowResized();
/// Check if one specific window flag is enabled
bool IsWindowState(ConfigFlags flag) => proxy.IsWindowState(flag);
/// Set window configuration state using flags
void SetWindowState(ConfigFlags flags) => proxy.SetWindowState(flags);
/// Clear window configuration state flags
void ClearWindowState(ConfigFlags flags) => proxy.ClearWindowState(flags);
/// Toggle window state: fullscreen/windowed, resizes monitor to match window resolution
void ToggleFullscreen() => raw.ToggleFullscreen();
/// Toggle window state: borderless windowed, resizes window to match monitor resolution
void ToggleBorderlessWindowed() => raw.ToggleBorderlessWindowed();
/// Set window state: maximized, if resizable
void MaximizeWindow() => raw.MaximizeWindow();
/// Set window state: minimized, if resizable
void MinimizeWindow() => raw.MinimizeWindow();
/// Restore window from being minimized/maximized
void RestoreWindow() => raw.RestoreWindow();
/// Set icon for window (single image, RGBA 32bit)
void SetWindowIcon(Image image) => proxy.SetWindowIcon(image);
/// Set icon for window (multiple images, RGBA 32bit)
void SetWindowIcons(List<Image> images, int count) => proxy.SetWindowIcons(images, count);
/// Set title for window
void SetWindowTitle(String title) => proxy.SetWindowTitle(title);
/// Set window position on screen
void SetWindowPosition(int x, int y) => raw.SetWindowPosition(x, y);
/// Set monitor for the current window
void SetWindowMonitor(int monitor) => raw.SetWindowMonitor(monitor);
/// Set window minimum dimensions (for FLAG_WINDOW_RESIZABLE)
void SetWindowMinSize(int width, int height) => raw.SetWindowMinSize(width, height);
/// Set window maximum dimensions (for FLAG_WINDOW_RESIZABLE)
void SetWindowMaxSize(int width, int height) => raw.SetWindowMaxSize(width, height);
/// Set window dimensions
void SetWindowSize(int width, int height) => raw.SetWindowSize(width, height);
/// Set window opacity [0.0f..1.0f]
void SetWindowOpacity(double opacity) => raw.SetWindowOpacity(opacity);
/// Set window focused
void SetWindowFocused() => raw.SetWindowFocused();
/// Get native window handle
int GetWindowHandle() => proxy.GetWindowHandle();
/// Get current screen width
int GetScreenWidth() => raw.GetScreenWidth();
/// Get current screen height
int GetScreenHeight() => raw.GetScreenHeight();
/// Get current render width (it considers HiDPI)
int GetRenderWidth() => raw.GetRenderWidth();
/// Get current render height (it considers HiDPI)
int GetRenderHeight() => raw.GetRenderHeight();
/// Get number of connected monitors
int GetMonitorCount() => raw.GetMonitorCount();
/// Get current monitor where window is placed
int GetCurrentMonitor() => raw.GetCurrentMonitor();
/// Get specified monitor position
Vector2 GetMonitorPosition(int monitor) => proxy.GetMonitorPosition(monitor);
/// Get specified monitor width (current video mode used by monitor)
int GetMonitorWidth(int monitor) => raw.GetMonitorWidth(monitor);
/// Get specified monitor height (current video mode used by monitor)
int GetMonitorHeight(int monitor) => raw.GetMonitorHeight(monitor);
/// Get specified monitor physical width in millimetres
int GetMonitorPhysicalWidth(int monitor) => raw.GetMonitorPhysicalWidth(monitor);
/// Get specified monitor physical height in millimetres
int GetMonitorPhysicalHeight(int monitor) => raw.GetMonitorPhysicalHeight(monitor);
/// Get specified monitor refresh rate
int GetMonitorRefreshRate(int monitor) => raw.GetMonitorRefreshRate(monitor);
/// Get window position XY on monitor
Vector2 GetWindowPosition() => proxy.GetWindowPosition();
/// Get window scale DPI factor
Vector2 GetWindowScaleDPI() => proxy.GetWindowScaleDPI();
/// Get the human-readable, UTF-8 encoded name of the specified monitor
String GetMonitorName(int monitor) => proxy.GetMonitorName(monitor);
/// Set clipboard text content
void SetClipboardText(String text) => proxy.SetClipboardText(text);
/// Get clipboard text content
String GetClipboardText() => proxy.GetClipboardText();
/// Get clipboard image content
Image GetClipboardImage() => proxy.GetClipboardImage();
/// Enable waiting for events on EndDrawing(), no automatic event polling
void EnableEventWaiting() => raw.EnableEventWaiting();
/// Disable waiting for events on EndDrawing(), automatic events polling
void DisableEventWaiting() => raw.DisableEventWaiting();

// Cursor-related functions
/// Shows cursor
void ShowCursor() => raw.ShowCursor();
/// Hides cursor
void HideCursor() => raw.HideCursor();
/// Check if cursor is not visible
bool IsCursorHidden() => raw.IsCursorHidden();
/// Enables cursor (unlock cursor)
void EnableCursor() => raw.EnableCursor();
/// Disables cursor (lock cursor)
void DisableCursor() => raw.DisableCursor();
/// Check if cursor is on the screen
bool IsCursorOnScreen() => raw.IsCursorOnScreen();

// Drawing-related functions
/// Set background color (framebuffer clear color)
void ClearBackground(Color color) => proxy.ClearBackground(color);
/// Setup canvas (framebuffer) to start drawing
void BeginDrawing() => raw.BeginDrawing();
/// End canvas drawing and swap buffers (double buffering)
void EndDrawing() => raw.EndDrawing();
/// Begin 2D mode with custom camera (2D)
void BeginMode2D(Camera2D camera) => proxy.BeginMode2D(camera);
/// Ends 2D mode with custom camera
void EndMode2D() => raw.EndMode2D();
/// Begin 3D mode with custom camera (3D)
void BeginMode3D(Camera3D camera) => proxy.BeginMode3D(camera);
/// Ends 3D mode and returns to default 2D orthographic mode
void EndMode3D() => raw.EndMode3D();
/// Begin drawing to render texture
void BeginTextureMode(RenderTexture2D target) => proxy.BeginTextureMode(target);
/// Ends drawing to render texture
void EndTextureMode() => raw.EndTextureMode();
/// Begin custom shader drawing
void BeginShaderMode(Shader shader) => proxy.BeginShaderMode(shader);
/// End custom shader drawing (use default shader)
void EndShaderMode() => raw.EndShaderMode();
/// Begin blending mode (alpha, additive, multiplied, subtract, custom)
void BeginBlendMode(BlendMode mode) => proxy.BeginBlendMode(mode);
/// End blending mode (reset to default: alpha blending)
void EndBlendMode() => raw.EndBlendMode();
/// Begin scissor mode (define screen area for following drawing)
void BeginScissorMode(int x, int y, int width, int height) => raw.BeginScissorMode(x, y, width, height);
/// End scissor mode
void EndScissorMode() => raw.EndScissorMode();
/// Begin stereo rendering (requires VR simulator)
void BeginVrStereoMode(VrStereoConfig config) => proxy.BeginVrStereoMode(config);
/// End stereo rendering (requires VR simulator)
void EndVrStereoMode() => raw.EndVrStereoMode();

// VR stereo config functions for VR simulator
/// Load VR stereo config for VR simulator device parameters
VrStereoConfig LoadVrStereoConfig(VrDeviceInfo device) => proxy.LoadVrStereoConfig(device);
/// Unload VR stereo config
void UnloadVrStereoConfig(VrStereoConfig config) => proxy.UnloadVrStereoConfig(config);

// Shader management functions
// NOTE: Shader functionality is not available on OpenGL 1.1
/// Load shader from files and bind default locations
Shader LoadShader(String vsFileName, String fsFileName) => proxy.LoadShader(vsFileName, fsFileName);
/// Load shader from code strings and bind default locations
Shader LoadShaderFromMemory(String vsCode, String fsCode) => proxy.LoadShaderFromMemory(vsCode, fsCode);
/// Check if a shader is valid (loaded on GPU)
bool IsShaderValid(Shader shader) => proxy.IsShaderValid(shader);
/// Get shader uniform location
int GetShaderLocation(Shader shader, String uniformName) => proxy.GetShaderLocation(shader, uniformName);
/// Get shader attribute location
int GetShaderLocationAttrib(Shader shader, String attribName) => proxy.GetShaderLocationAttrib(shader, attribName);
/// Set shader uniform value
void SetShaderValue(Shader shader, int locIndex, TypedData value, ShaderUniformDataType uniformType) => proxy.SetShaderValue(shader, locIndex, value, uniformType);
/// Set shader uniform value vector
void SetShaderValueV(Shader shader, int locIndex, TypedData value, ShaderUniformDataType uniformType, int count) => proxy.SetShaderValueV(shader, locIndex, value, uniformType, count);
/// Set shader uniform value (matrix 4x4)
void SetShaderValueMatrix(Shader shader, int locIndex, Matrix mat) => proxy.SetShaderValueMatrix(shader, locIndex, mat);
/// Set shader uniform value and bind the texture (sampler2d)
void SetShaderValueTexture(Shader shader, int locIndex, Texture2D texture) => proxy.SetShaderValueTexture(shader, locIndex, texture);
/// Unload shader from GPU memory (VRAM)
void UnloadShader(Shader shader) => proxy.UnloadShader(shader);

// Screen-space-related functions
/// Get a ray trace from screen position (i.e mouse)
Ray GetScreenToWorldRay(Vector2 position, Camera camera) => proxy.GetScreenToWorldRay(position, camera);
/// Get a ray trace from screen position (i.e mouse) in a viewport
Ray GetScreenToWorldRayEx(Vector2 position, Camera camera, int width, int height) => proxy.GetScreenToWorldRayEx(position, camera, width, height);
/// Get the screen space position for a 3d world space position
Vector2 GetWorldToScreen(Vector3 position, Camera camera) => proxy.GetWorldToScreen(position, camera);
/// Get size position for a 3d world space position
Vector2 GetWorldToScreenEx(Vector3 position, Camera camera, int width, int height) => proxy.GetWorldToScreenEx(position, camera, width, height);
/// Get the screen space position for a 2d camera world space position
Vector2 GetWorldToScreen2D(Vector2 position, Camera2D camera) => proxy.GetWorldToScreen2D(position, camera);
/// Get the world space position for a 2d camera screen space position
Vector2 GetScreenToWorld2D(Vector2 position, Camera2D camera) => proxy.GetScreenToWorld2D(position, camera);
/// Get camera transform matrix (view matrix)
Matrix GetCameraMatrix(Camera camera) => proxy.GetCameraMatrix(camera);
/// Get camera 2d transform matrix
Matrix GetCameraMatrix2D(Camera2D camera) => proxy.GetCameraMatrix2D(camera);

// Timing-related functions
/// Set target FPS (maximum)
void SetTargetFPS(int fps) => raw.SetTargetFPS(fps);
/// Get time in seconds for last frame drawn (delta time)
double GetFrameTime() => raw.GetFrameTime();
/// Get elapsed time in seconds since InitWindow()
double GetTime() => raw.GetTime();
/// Get current FPS
int GetFPS() => raw.GetFPS();

// Custom frame control functions
// NOTE: Those functions are intended for advanced users that want full control over the frame processing
// By default EndDrawing() does this job: draws everything + SwapScreenBuffer() + manage frame timing + PollInputEvents()
// To avoid that behaviour and control frame processes manually, enable in config.h: SUPPORT_CUSTOM_FRAME_CONTROL
/// Swap back buffer with front buffer (screen drawing)
void SwapScreenBuffer() => raw.SwapScreenBuffer();
/// Register all input events
void PollInputEvents() => raw.PollInputEvents();
/// Wait for some time (halt program execution)
void WaitTime(double seconds) => raw.WaitTime(seconds);

// Random values generation functions
/// Set the seed for the random number generator
void SetRandomSeed(int seed) => raw.SetRandomSeed(seed);
/// Get a random value between min and max (both included)
int GetRandomValue(int min, int max) => raw.GetRandomValue(min, max);
/// Load random values sequence, no values repeated
List<int> LoadRandomSequence(int count, int min, int max) => proxy.LoadRandomSequence(count, min, max);
/// Unload random values sequence
void UnloadRandomSequence(List<int> sequence) => proxy.UnloadRandomSequence(sequence);

// Misc. functions
/// Takes a screenshot of current screen (filename extension defines format)
void TakeScreenshot(String fileName) => proxy.TakeScreenshot(fileName);
/// Setup init configuration flags (view FLAGS)
void SetConfigFlags(ConfigFlags flags) => proxy.SetConfigFlags(flags);
/// Open URL with default system browser (if available)
void OpenURL(String url) => proxy.OpenURL(url);

// Logging system
/// Set the current threshold (minimum) log level
void SetTraceLogLevel(TraceLogLevel logLevel) => proxy.SetTraceLogLevel(logLevel);
/// Show trace log messages (LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_ERROR...)
void TraceLog(TraceLogLevel logLevel, String text, List<Object> args) => proxy.TraceLog(logLevel, text, args);
/// Set custom trace log
void SetTraceLogCallback(TraceLogCallback callback) => proxy.SetTraceLogCallback(callback);

// Memory management, using internal allocators
/// Internal memory allocator
int MemAlloc(int size) => proxy.MemAlloc(size);
/// Internal memory reallocator
int MemRealloc(int ptr, int size) => proxy.MemRealloc(ptr, size);
/// Internal memory free
void MemFree(int ptr) => proxy.MemFree(ptr);

// File system management functions
/// Load file data as byte array (read)
Uint8List LoadFileData(String fileName) => proxy.LoadFileData(fileName);
/// Unload file data allocated by LoadFileData()
void UnloadFileData(Uint8List data) => proxy.UnloadFileData(data);
/// Save data to file from byte array (write), returns true on success
bool SaveFileData(String fileName, Uint8List data) => proxy.SaveFileData(fileName, data);
/// Export data to code (.h), returns true on success
bool ExportDataAsCode(Uint8List data, String fileName) => proxy.ExportDataAsCode(data, fileName);
/// Load text data from file (read), returns a '\0' terminated string
String LoadFileText(String fileName) => proxy.LoadFileText(fileName);
/// Unload file text data allocated by LoadFileText()
void UnloadFileText(String text) => proxy.UnloadFileText(text);
/// Save text data to file (write), string must be '\0' terminated, returns true on success
bool SaveFileText(String fileName, String text) => proxy.SaveFileText(fileName, text);

// File access custom callbacks
// WARNING: Callbacks setup is intended for advanced users
/// Set custom file binary data loader
void SetLoadFileDataCallback(LoadFileDataCallback callback) => proxy.SetLoadFileDataCallback(callback);
/// Set custom file binary data saver
void SetSaveFileDataCallback(SaveFileDataCallback callback) => proxy.SetSaveFileDataCallback(callback);
/// Set custom file text data loader
void SetLoadFileTextCallback(LoadFileTextCallback callback) => proxy.SetLoadFileTextCallback(callback);
/// Set custom file text data saver
void SetSaveFileTextCallback(SaveFileTextCallback callback) => proxy.SetSaveFileTextCallback(callback);

/// Rename file (if exists)
int FileRename(String fileName, String fileRename) => proxy.FileRename(fileName, fileRename);
/// Remove file (if exists)
int FileRemove(String fileName) => proxy.FileRemove(fileName);
/// Copy file from one path to another, dstPath created if it doesn't exist
int FileCopy(String srcPath, String dstPath) => proxy.FileCopy(srcPath, dstPath);
/// Move file from one directory to another, dstPath created if it doesn't exist
int FileMove(String srcPath, String dstPath) => proxy.FileMove(srcPath, dstPath);
/// Replace text in an existing file
int FileTextReplace(String fileName, String search, String replacement) => proxy.FileTextReplace(fileName, search, replacement);
/// Find text in existing file
int FileTextFindIndex(String fileName, String search) => proxy.FileTextFindIndex(fileName, search);
/// Check if file exists
bool FileExists(String fileName) => proxy.FileExists(fileName);
/// Check if a directory path exists
bool DirectoryExists(String dirPath) => proxy.DirectoryExists(dirPath);
/// Check file extension (recommended include point: .png, .wav)
bool IsFileExtension(String fileName, String ext) => proxy.IsFileExtension(fileName, ext);
/// Get file length in bytes (NOTE: GetFileSize() conflicts with windows.h)
int GetFileLength(String fileName) => proxy.GetFileLength(fileName);
/// Get file modification time (last write time)
int GetFileModTime(String fileName) => proxy.GetFileModTime(fileName);
/// Get pointer to extension for a filename string (includes dot: '.png')
String GetFileExtension(String fileName) => proxy.GetFileExtension(fileName);
/// Get pointer to filename for a path string
String GetFileName(String filePath) => proxy.GetFileName(filePath);
/// Get filename string without extension (uses static string)
String GetFileNameWithoutExt(String filePath) => proxy.GetFileNameWithoutExt(filePath);
/// Get full path for a given fileName with path (uses static string)
String GetDirectoryPath(String filePath) => proxy.GetDirectoryPath(filePath);
/// Get previous directory path for a given path (uses static string)
String GetPrevDirectoryPath(String dirPath) => proxy.GetPrevDirectoryPath(dirPath);
/// Get current working directory (uses static string)
String GetWorkingDirectory() => proxy.GetWorkingDirectory();
/// Get the directory of the running application (uses static string)
String GetApplicationDirectory() => proxy.GetApplicationDirectory();
/// Create directories (including full path requested), returns 0 on success
int MakeDirectory(String dirPath) => proxy.MakeDirectory(dirPath);
/// Change working directory, return true on success
bool ChangeDirectory(String dirPath) => proxy.ChangeDirectory(dirPath);
/// Check if a given path is a file or a directory
bool IsPathFile(String path) => proxy.IsPathFile(path);
/// Check if fileName is valid for the platform/OS
bool IsFileNameValid(String fileName) => proxy.IsFileNameValid(fileName);
/// Load directory filepaths, files and directories, no subdirs scan
FilePathList LoadDirectoryFiles(String dirPath) => proxy.LoadDirectoryFiles(dirPath);
/// Load directory filepaths with extension filtering and subdir scan; some filters available: "*.*", "FILES*", "DIRS*"
FilePathList LoadDirectoryFilesEx(String basePath, String filter, bool scanSubdirs) => proxy.LoadDirectoryFilesEx(basePath, filter, scanSubdirs);
/// Unload filepaths
void UnloadDirectoryFiles(FilePathList files) => proxy.UnloadDirectoryFiles(files);
/// Check if a file has been dropped into window
bool IsFileDropped() => raw.IsFileDropped();
/// Load dropped filepaths
FilePathList LoadDroppedFiles() => proxy.LoadDroppedFiles();
/// Unload dropped filepaths
void UnloadDroppedFiles(FilePathList files) => proxy.UnloadDroppedFiles(files);
/// Get the file count in a directory
int GetDirectoryFileCount(String dirPath) => proxy.GetDirectoryFileCount(dirPath);
/// Get the file count in a directory with extension filtering and recursive directory scan. Use 'DIR' in the filter string to include directories in the result
int GetDirectoryFileCountEx(String basePath, String filter, bool scanSubdirs) => proxy.GetDirectoryFileCountEx(basePath, filter, scanSubdirs);

// Compression/Encoding functionality
/// Compress data (DEFLATE algorithm), memory must be MemFree()
Uint8List CompressData(Uint8List data) => proxy.CompressData(data);
/// Decompress data (DEFLATE algorithm), memory must be MemFree()
Uint8List DecompressData(Uint8List compData) => proxy.DecompressData(compData);
/// Encode data to Base64 string (includes NULL terminator), memory must be MemFree()
String EncodeDataBase64(Uint8List data) => proxy.EncodeDataBase64(data);
/// Decode Base64 string (expected NULL terminated), memory must be MemFree()
Uint8List DecodeDataBase64(Uint8List data) => proxy.DecodeDataBase64(data);
/// Compute CRC32 hash code
int ComputeCRC32(Uint8List data) => proxy.ComputeCRC32(data);
/// Compute MD5 hash code, returns static int[4] (16 bytes)
Uint8List ComputeMD5(Uint8List data) => proxy.ComputeMD5(data);
/// Compute SHA1 hash code, returns static int[5] (20 bytes)
Uint8List ComputeSHA1(Uint8List data) => proxy.ComputeSHA1(data);
/// Compute SHA256 hash code, returns static int[8] (32 bytes)
Uint8List ComputeSHA256(Uint8List data) => proxy.ComputeSHA256(data);

// Automation events functionality
/// Load automation events list from file, NULL for empty list, capacity = MAX_AUTOMATION_EVENTS
AutomationEventList LoadAutomationEventList(String fileName) => proxy.LoadAutomationEventList(fileName);
/// Unload automation events list from file
void UnloadAutomationEventList(AutomationEventList list) => proxy.UnloadAutomationEventList(list);
/// Export automation events list as text file
bool ExportAutomationEventList(AutomationEventList list, String fileName) => proxy.ExportAutomationEventList(list, fileName);
/// Set automation event list to record to
void SetAutomationEventList(List<AutomationEventList> list) => proxy.SetAutomationEventList(list);
/// Set automation event internal base frame to start recording
void SetAutomationEventBaseFrame(int frame) => raw.SetAutomationEventBaseFrame(frame);
/// Start recording automation events (AutomationEventList must be set)
void StartAutomationEventRecording() => raw.StartAutomationEventRecording();
/// Stop recording automation events
void StopAutomationEventRecording() => raw.StopAutomationEventRecording();
/// Play a recorded automation event
void PlayAutomationEvent(AutomationEvent event) => proxy.PlayAutomationEvent(event);

//------------------------------------------------------------------------------------
// Input Handling Functions (Module: core)
//------------------------------------------------------------------------------------

// Input-related functions: keyboard
/// Check if a key has been pressed once
bool IsKeyPressed(int key) => proxy.IsKeyPressed(key);
/// Check if a key has been pressed again
bool IsKeyPressedRepeat(int key) => proxy.IsKeyPressedRepeat(key);
/// Check if a key is being pressed
bool IsKeyDown(int key) => proxy.IsKeyDown(key);
/// Check if a key has been released once
bool IsKeyReleased(int key) => proxy.IsKeyReleased(key);
/// Check if a key is NOT being pressed
bool IsKeyUp(int key) => proxy.IsKeyUp(key);
/// Get key pressed (keycode), call it multiple times for keys queued, returns 0 when the queue is empty
int GetKeyPressed() => proxy.GetKeyPressed();
/// Get char pressed (unicode), call it multiple times for chars queued, returns 0 when the queue is empty
int GetCharPressed() => raw.GetCharPressed();
/// Get name of a QWERTY key on the current keyboard layout (eg returns string 'q' for KEY_A on an AZERTY keyboard)
String GetKeyName(int key) => raw.GetKeyName(key);
/// Set a custom key to exit program (default is ESC)
void SetExitKey(int key) => proxy.SetExitKey(key);

// Input-related functions: gamepads
/// Check if a gamepad is available
bool IsGamepadAvailable(int gamepad) => raw.IsGamepadAvailable(gamepad);
/// Get gamepad internal name id
String GetGamepadName(int gamepad) => proxy.GetGamepadName(gamepad);
/// Check if a gamepad button has been pressed once
bool IsGamepadButtonPressed(int gamepad, int button) => proxy.IsGamepadButtonPressed(gamepad, button);
/// Check if a gamepad button is being pressed
bool IsGamepadButtonDown(int gamepad, int button) => proxy.IsGamepadButtonDown(gamepad, button);
/// Check if a gamepad button has been released once
bool IsGamepadButtonReleased(int gamepad, int button) => proxy.IsGamepadButtonReleased(gamepad, button);
/// Check if a gamepad button is NOT being pressed
bool IsGamepadButtonUp(int gamepad, int button) => proxy.IsGamepadButtonUp(gamepad, button);
/// Get the last gamepad button pressed
int GetGamepadButtonPressed() => proxy.GetGamepadButtonPressed();
/// Get axis count for a gamepad
int GetGamepadAxisCount(int gamepad) => raw.GetGamepadAxisCount(gamepad);
/// Get movement value for a gamepad axis
double GetGamepadAxisMovement(int gamepad, int axis) => proxy.GetGamepadAxisMovement(gamepad, axis);
/// Set internal gamepad mappings (SDL_GameControllerDB)
int SetGamepadMappings(String mappings) => proxy.SetGamepadMappings(mappings);
/// Set gamepad vibration for both motors (duration in seconds)
void SetGamepadVibration(int gamepad, double leftMotor, double rightMotor, double duration) => raw.SetGamepadVibration(gamepad, leftMotor, rightMotor, duration);

// Input-related functions: mouse
/// Check if a mouse button has been pressed once
bool IsMouseButtonPressed(int button) => proxy.IsMouseButtonPressed(button);
/// Check if a mouse button is being pressed
bool IsMouseButtonDown(int button) => proxy.IsMouseButtonDown(button);
/// Check if a mouse button has been released once
bool IsMouseButtonReleased(int button) => proxy.IsMouseButtonReleased(button);
/// Check if a mouse button is NOT being pressed
bool IsMouseButtonUp(int button) => proxy.IsMouseButtonUp(button);
/// Get mouse position X
int GetMouseX() => raw.GetMouseX();
/// Get mouse position Y
int GetMouseY() => raw.GetMouseY();
/// Get mouse position XY
Vector2 GetMousePosition() => proxy.GetMousePosition();
/// Get mouse delta between frames
Vector2 GetMouseDelta() => proxy.GetMouseDelta();
/// Set mouse position XY
void SetMousePosition(int x, int y) => raw.SetMousePosition(x, y);
/// Set mouse offset
void SetMouseOffset(int offsetX, int offsetY) => raw.SetMouseOffset(offsetX, offsetY);
/// Set mouse scaling
void SetMouseScale(double scaleX, double scaleY) => raw.SetMouseScale(scaleX, scaleY);
/// Get mouse wheel movement for X or Y, whichever is larger
double GetMouseWheelMove() => raw.GetMouseWheelMove();
/// Get mouse wheel movement for both X and Y
Vector2 GetMouseWheelMoveV() => proxy.GetMouseWheelMoveV();
/// Set mouse cursor
void SetMouseCursor(int cursor) => proxy.SetMouseCursor(cursor);

// Input-related functions: touch
/// Get touch position X for touch point 0 (relative to screen size)
int GetTouchX() => raw.GetTouchX();
/// Get touch position Y for touch point 0 (relative to screen size)
int GetTouchY() => raw.GetTouchY();
/// Get touch position XY for a touch point index (relative to screen size)
Vector2 GetTouchPosition(int index) => proxy.GetTouchPosition(index);
/// Get touch point identifier for given index
int GetTouchPointId(int index) => raw.GetTouchPointId(index);
/// Get number of touch points
int GetTouchPointCount() => raw.GetTouchPointCount();

//------------------------------------------------------------------------------------
// Gestures and Touch Handling Functions (Module: rgestures)
//------------------------------------------------------------------------------------
/// Enable a set of gestures using flags
void SetGesturesEnabled(int flags) => proxy.SetGesturesEnabled(flags);
/// Check if a gesture have been detected
bool IsGestureDetected(int gesture) => proxy.IsGestureDetected(gesture);
/// Get latest detected gesture
int GetGestureDetected() => proxy.GetGestureDetected();
/// Get gesture hold time in seconds
double GetGestureHoldDuration() => raw.GetGestureHoldDuration();
/// Get gesture drag vector
Vector2 GetGestureDragVector() => proxy.GetGestureDragVector();
/// Get gesture drag angle
double GetGestureDragAngle() => raw.GetGestureDragAngle();
/// Get gesture pinch delta
Vector2 GetGesturePinchVector() => proxy.GetGesturePinchVector();
/// Get gesture pinch angle
double GetGesturePinchAngle() => raw.GetGesturePinchAngle();

//------------------------------------------------------------------------------------
// Camera System Functions (Module: rcamera)
//------------------------------------------------------------------------------------
/// Update camera position for selected mode
void UpdateCamera(List<Camera> camera, int mode) => proxy.UpdateCamera(camera, mode);
/// Update camera movement/rotation
void UpdateCameraPro(List<Camera> camera, Vector3 movement, Vector3 rotation, double zoom) => proxy.UpdateCameraPro(camera, movement, rotation, zoom);


