// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'models_proxy.dart' as proxy;
import 'dart:typed_data';
import 'raylib_const.dart';
import 'structs.dart';

// Basic geometric 3D shapes drawing functions
/// Draw a line in 3D world space
const DrawLine3D = proxy.DrawLine3D;
/// Draw a point in 3D space, actually a small line
const DrawPoint3D = proxy.DrawPoint3D;
/// Draw a circle in 3D world space
const DrawCircle3D = proxy.DrawCircle3D;
/// Draw a color-filled triangle (vertex in counter-clockwise order!)
const DrawTriangle3D = proxy.DrawTriangle3D;
/// Draw a triangle strip defined by points
const DrawTriangleStrip3D = proxy.DrawTriangleStrip3D;
/// Draw cube
const DrawCube = proxy.DrawCube;
/// Draw cube (Vector version)
const DrawCubeV = proxy.DrawCubeV;
/// Draw cube wires
const DrawCubeWires = proxy.DrawCubeWires;
/// Draw cube wires (Vector version)
const DrawCubeWiresV = proxy.DrawCubeWiresV;
/// Draw sphere
const DrawSphere = proxy.DrawSphere;
/// Draw sphere with extended parameters
const DrawSphereEx = proxy.DrawSphereEx;
/// Draw sphere wires
const DrawSphereWires = proxy.DrawSphereWires;
/// Draw a cylinder/cone
const DrawCylinder = proxy.DrawCylinder;
/// Draw a cylinder with base at startPos and top at endPos
const DrawCylinderEx = proxy.DrawCylinderEx;
/// Draw a cylinder/cone wires
const DrawCylinderWires = proxy.DrawCylinderWires;
/// Draw a cylinder wires with base at startPos and top at endPos
const DrawCylinderWiresEx = proxy.DrawCylinderWiresEx;
/// Draw a capsule with the center of its sphere caps at startPos and endPos
const DrawCapsule = proxy.DrawCapsule;
/// Draw capsule wireframe with the center of its sphere caps at startPos and endPos
const DrawCapsuleWires = proxy.DrawCapsuleWires;
/// Draw a plane XZ
const DrawPlane = proxy.DrawPlane;
/// Draw a ray line
const DrawRay = proxy.DrawRay;
/// Draw a grid (centered at (0, 0, 0))
void DrawGrid(int slices, double spacing) => raw.DrawGrid(slices, spacing);

//------------------------------------------------------------------------------------
// Model 3d Loading and Drawing Functions (Module: models)
//------------------------------------------------------------------------------------

// Model management functions
/// Load model from files (meshes and materials)
const LoadModel = proxy.LoadModel;
/// Load model from generated mesh (default material)
const LoadModelFromMesh = proxy.LoadModelFromMesh;
/// Check if a model is valid (loaded in GPU, VAO/VBOs)
const IsModelValid = proxy.IsModelValid;
/// Unload model (including meshes) from memory (RAM and/or VRAM)
const UnloadModel = proxy.UnloadModel;
/// Compute model bounding box limits (considers all meshes)
const GetModelBoundingBox = proxy.GetModelBoundingBox;

// Model drawing functions
/// Draw a model (with texture if set)
const DrawModel = proxy.DrawModel;
/// Draw a model with extended parameters
const DrawModelEx = proxy.DrawModelEx;
/// Draw a model wires (with texture if set)
const DrawModelWires = proxy.DrawModelWires;
/// Draw a model wires (with texture if set) with extended parameters
const DrawModelWiresEx = proxy.DrawModelWiresEx;
/// Draw bounding box (wires)
const DrawBoundingBox = proxy.DrawBoundingBox;
/// Draw a billboard texture
const DrawBillboard = proxy.DrawBillboard;
/// Draw a billboard texture defined by source
const DrawBillboardRec = proxy.DrawBillboardRec;
/// Draw a billboard texture defined by source and rotation
const DrawBillboardPro = proxy.DrawBillboardPro;

// Mesh management functions
/// Upload mesh vertex data in GPU and provide VAO/VBO ids
const UploadMesh = proxy.UploadMesh;
/// Update mesh vertex data in GPU for a specific buffer index
const UpdateMeshBuffer = proxy.UpdateMeshBuffer;
/// Unload mesh data from CPU and GPU
const UnloadMesh = proxy.UnloadMesh;
/// Draw a 3d mesh with material and transform
const DrawMesh = proxy.DrawMesh;
/// Draw multiple mesh instances with material and different transforms
const DrawMeshInstanced = proxy.DrawMeshInstanced;
/// Compute mesh bounding box limits
const GetMeshBoundingBox = proxy.GetMeshBoundingBox;
/// Compute mesh tangents
const GenMeshTangents = proxy.GenMeshTangents;
/// Export mesh data to file, returns true on success
const ExportMesh = proxy.ExportMesh;
/// Export mesh as code file (.h) defining multiple arrays of vertex attributes
const ExportMeshAsCode = proxy.ExportMeshAsCode;

// Mesh generation functions
/// Generate polygonal mesh
const GenMeshPoly = proxy.GenMeshPoly;
/// Generate plane mesh (with subdivisions)
const GenMeshPlane = proxy.GenMeshPlane;
/// Generate cuboid mesh
const GenMeshCube = proxy.GenMeshCube;
/// Generate sphere mesh (standard sphere)
const GenMeshSphere = proxy.GenMeshSphere;
/// Generate half-sphere mesh (no bottom cap)
const GenMeshHemiSphere = proxy.GenMeshHemiSphere;
/// Generate cylinder mesh
const GenMeshCylinder = proxy.GenMeshCylinder;
/// Generate cone/pyramid mesh
const GenMeshCone = proxy.GenMeshCone;
/// Generate torus mesh
const GenMeshTorus = proxy.GenMeshTorus;
/// Generate trefoil knot mesh
const GenMeshKnot = proxy.GenMeshKnot;
/// Generate heightmap mesh from image data
const GenMeshHeightmap = proxy.GenMeshHeightmap;
/// Generate cubes-based map mesh from image data
const GenMeshCubicmap = proxy.GenMeshCubicmap;

// Material loading/unloading functions
/// Load materials from model file
const LoadMaterials = proxy.LoadMaterials;
/// Load default material (Supports: DIFFUSE, SPECULAR, NORMAL maps)
const LoadMaterialDefault = proxy.LoadMaterialDefault;
/// Check if a material is valid (shader assigned, map textures loaded in GPU)
const IsMaterialValid = proxy.IsMaterialValid;
/// Unload material from GPU memory (VRAM)
const UnloadMaterial = proxy.UnloadMaterial;
/// Set texture for a material map type (MATERIAL_MAP_DIFFUSE, MATERIAL_MAP_SPECULAR...)
const SetMaterialTexture = proxy.SetMaterialTexture;
/// Set material for a mesh
const SetModelMeshMaterial = proxy.SetModelMeshMaterial;

// Model animations loading/unloading functions
/// Load model animations from file
const LoadModelAnimations = proxy.LoadModelAnimations;
/// Update model animation pose (vertex buffers and bone matrices)
const UpdateModelAnimation = proxy.UpdateModelAnimation;
/// Update model animation pose, blending two animations
const UpdateModelAnimationEx = proxy.UpdateModelAnimationEx;
/// Unload animation array data
const UnloadModelAnimations = proxy.UnloadModelAnimations;
/// Check model animation skeleton match
const IsModelAnimationValid = proxy.IsModelAnimationValid;

// Collision detection functions
/// Check collision between two spheres
const CheckCollisionSpheres = proxy.CheckCollisionSpheres;
/// Check collision between two bounding boxes
const CheckCollisionBoxes = proxy.CheckCollisionBoxes;
/// Check collision between box and sphere
const CheckCollisionBoxSphere = proxy.CheckCollisionBoxSphere;
/// Get collision info between ray and sphere
const GetRayCollisionSphere = proxy.GetRayCollisionSphere;
/// Get collision info between ray and box
const GetRayCollisionBox = proxy.GetRayCollisionBox;
/// Get collision info between ray and mesh
const GetRayCollisionMesh = proxy.GetRayCollisionMesh;
/// Get collision info between ray and triangle
const GetRayCollisionTriangle = proxy.GetRayCollisionTriangle;
/// Get collision info between ray and quad
const GetRayCollisionQuad = proxy.GetRayCollisionQuad;


