// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'shapes_proxy.dart' as proxy;
import 'structs.dart';

// NOTE: It can be useful when using basic shapes and one single font,
// defining a font char white rectangle would allow drawing everything in a single draw call
/// Set texture and rectangle to be used on shapes drawing
void SetShapesTexture(Texture2D texture, Rectangle source) => proxy.SetShapesTexture(texture, source);
/// Get texture that is used for shapes drawing
Texture2D GetShapesTexture() => proxy.GetShapesTexture();
/// Get texture source rectangle that is used for shapes drawing
Rectangle GetShapesTextureRectangle() => proxy.GetShapesTextureRectangle();

// Basic shapes drawing functions
/// Draw a pixel using geometry [Can be slow, use with care]
void DrawPixel(int posX, int posY, Color color) => proxy.DrawPixel(posX, posY, color);
/// Draw a pixel using geometry (Vector version) [Can be slow, use with care]
void DrawPixelV(Vector2 position, Color color) => proxy.DrawPixelV(position, color);
/// Draw a line
void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color) => proxy.DrawLine(startPosX, startPosY, endPosX, endPosY, color);
/// Draw a line (using gl lines)
void DrawLineV(Vector2 startPos, Vector2 endPos, Color color) => raw.DrawLineV(startPos, endPos, color);
/// Draw a line (using triangles/quads)
void DrawLineEx(Vector2 startPos, Vector2 endPos, double thick, Color color) => raw.DrawLineEx(startPos, endPos, thick, color);
/// Draw lines sequence (using gl lines)
void DrawLineStrip(List<Vector2> points, int pointCount, Color color) => raw.DrawLineStrip(points, pointCount, color);
/// Draw line segment cubic-bezier in-out interpolation
void DrawLineBezier(Vector2 startPos, Vector2 endPos, double thick, Color color) => raw.DrawLineBezier(startPos, endPos, thick, color);
/// Draw a dashed line
void DrawLineDashed(Vector2 startPos, Vector2 endPos, int dashSize, int spaceSize, Color color) => raw.DrawLineDashed(startPos, endPos, dashSize, spaceSize, color);
/// Draw a color-filled circle
void DrawCircle(int centerX, int centerY, double radius, Color color) => raw.DrawCircle(centerX, centerY, radius, color);
/// Draw a color-filled circle (Vector version)
void DrawCircleV(Vector2 center, double radius, Color color) => raw.DrawCircleV(center, radius, color);
/// Draw a gradient-filled circle
void DrawCircleGradient(Vector2 center, double radius, Color inner, Color outer) => raw.DrawCircleGradient(center, radius, inner, outer);
/// Draw a piece of a circle
void DrawCircleSector(Vector2 center, double radius, double startAngle, double endAngle, int segments, Color color) => raw.DrawCircleSector(center, radius, startAngle, endAngle, segments, color);
/// Draw circle sector outline
void DrawCircleSectorLines(Vector2 center, double radius, double startAngle, double endAngle, int segments, Color color) => raw.DrawCircleSectorLines(center, radius, startAngle, endAngle, segments, color);
/// Draw circle outline
void DrawCircleLines(int centerX, int centerY, double radius, Color color) => raw.DrawCircleLines(centerX, centerY, radius, color);
/// Draw circle outline (Vector version)
void DrawCircleLinesV(Vector2 center, double radius, Color color) => raw.DrawCircleLinesV(center, radius, color);
/// Draw ellipse
void DrawEllipse(int centerX, int centerY, double radiusH, double radiusV, Color color) => raw.DrawEllipse(centerX, centerY, radiusH, radiusV, color);
/// Draw ellipse (Vector version)
void DrawEllipseV(Vector2 center, double radiusH, double radiusV, Color color) => raw.DrawEllipseV(center, radiusH, radiusV, color);
/// Draw ellipse outline
void DrawEllipseLines(int centerX, int centerY, double radiusH, double radiusV, Color color) => raw.DrawEllipseLines(centerX, centerY, radiusH, radiusV, color);
/// Draw ellipse outline (Vector version)
void DrawEllipseLinesV(Vector2 center, double radiusH, double radiusV, Color color) => raw.DrawEllipseLinesV(center, radiusH, radiusV, color);
/// Draw ring
void DrawRing(Vector2 center, double innerRadius, double outerRadius, double startAngle, double endAngle, int segments, Color color) => raw.DrawRing(center, innerRadius, outerRadius, startAngle, endAngle, segments, color);
/// Draw ring outline
void DrawRingLines(Vector2 center, double innerRadius, double outerRadius, double startAngle, double endAngle, int segments, Color color) => raw.DrawRingLines(center, innerRadius, outerRadius, startAngle, endAngle, segments, color);
/// Draw a color-filled rectangle
void DrawRectangle(int posX, int posY, int width, int height, Color color) => raw.DrawRectangle(posX, posY, width, height, color);
/// Draw a color-filled rectangle (Vector version)
void DrawRectangleV(Vector2 position, Vector2 size, Color color) => raw.DrawRectangleV(position, size, color);
/// Draw a color-filled rectangle
void DrawRectangleRec(Rectangle rec, Color color) => raw.DrawRectangleRec(rec, color);
/// Draw a color-filled rectangle with pro parameters
void DrawRectanglePro(Rectangle rec, Vector2 origin, double rotation, Color color) => raw.DrawRectanglePro(rec, origin, rotation, color);
/// Draw a vertical-gradient-filled rectangle
void DrawRectangleGradientV(int posX, int posY, int width, int height, Color top, Color bottom) => raw.DrawRectangleGradientV(posX, posY, width, height, top, bottom);
/// Draw a horizontal-gradient-filled rectangle
void DrawRectangleGradientH(int posX, int posY, int width, int height, Color left, Color right) => raw.DrawRectangleGradientH(posX, posY, width, height, left, right);
/// Draw a gradient-filled rectangle with custom vertex colors
void DrawRectangleGradientEx(Rectangle rec, Color topLeft, Color bottomLeft, Color bottomRight, Color topRight) => raw.DrawRectangleGradientEx(rec, topLeft, bottomLeft, bottomRight, topRight);
/// Draw rectangle outline
void DrawRectangleLines(int posX, int posY, int width, int height, Color color) => raw.DrawRectangleLines(posX, posY, width, height, color);
/// Draw rectangle outline with extended parameters
void DrawRectangleLinesEx(Rectangle rec, double lineThick, Color color) => raw.DrawRectangleLinesEx(rec, lineThick, color);
/// Draw rectangle with rounded edges
void DrawRectangleRounded(Rectangle rec, double roundness, int segments, Color color) => raw.DrawRectangleRounded(rec, roundness, segments, color);
/// Draw rectangle lines with rounded edges
void DrawRectangleRoundedLines(Rectangle rec, double roundness, int segments, Color color) => raw.DrawRectangleRoundedLines(rec, roundness, segments, color);
/// Draw rectangle with rounded edges outline
void DrawRectangleRoundedLinesEx(Rectangle rec, double roundness, int segments, double lineThick, Color color) => raw.DrawRectangleRoundedLinesEx(rec, roundness, segments, lineThick, color);
/// Draw a color-filled triangle (vertex in counter-clockwise order!)
void DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color) => raw.DrawTriangle(v1, v2, v3, color);
/// Draw triangle outline (vertex in counter-clockwise order!)
void DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color) => raw.DrawTriangleLines(v1, v2, v3, color);
/// Draw a triangle fan defined by points (first vertex is the center)
void DrawTriangleFan(List<Vector2> points, int pointCount, Color color) => raw.DrawTriangleFan(points, pointCount, color);
/// Draw a triangle strip defined by points
void DrawTriangleStrip(List<Vector2> points, int pointCount, Color color) => raw.DrawTriangleStrip(points, pointCount, color);
/// Draw a regular polygon (Vector version)
void DrawPoly(Vector2 center, int sides, double radius, double rotation, Color color) => raw.DrawPoly(center, sides, radius, rotation, color);
/// Draw a polygon outline of n sides
void DrawPolyLines(Vector2 center, int sides, double radius, double rotation, Color color) => raw.DrawPolyLines(center, sides, radius, rotation, color);
/// Draw a polygon outline of n sides with extended parameters
void DrawPolyLinesEx(Vector2 center, int sides, double radius, double rotation, double lineThick, Color color) => raw.DrawPolyLinesEx(center, sides, radius, rotation, lineThick, color);

// Splines drawing functions
/// Draw spline: Linear, minimum 2 points
void DrawSplineLinear(List<Vector2> points, int pointCount, double thick, Color color) => raw.DrawSplineLinear(points, pointCount, thick, color);
/// Draw spline: B-Spline, minimum 4 points
void DrawSplineBasis(List<Vector2> points, int pointCount, double thick, Color color) => raw.DrawSplineBasis(points, pointCount, thick, color);
/// Draw spline: Catmull-Rom, minimum 4 points
void DrawSplineCatmullRom(List<Vector2> points, int pointCount, double thick, Color color) => raw.DrawSplineCatmullRom(points, pointCount, thick, color);
/// Draw spline: Quadratic Bezier, minimum 3 points (1 control point): [p1, c2, p3, c4...]
void DrawSplineBezierQuadratic(List<Vector2> points, int pointCount, double thick, Color color) => raw.DrawSplineBezierQuadratic(points, pointCount, thick, color);
/// Draw spline: Cubic Bezier, minimum 4 points (2 control points): [p1, c2, c3, p4, c5, c6...]
void DrawSplineBezierCubic(List<Vector2> points, int pointCount, double thick, Color color) => raw.DrawSplineBezierCubic(points, pointCount, thick, color);
/// Draw spline segment: Linear, 2 points
void DrawSplineSegmentLinear(Vector2 p1, Vector2 p2, double thick, Color color) => raw.DrawSplineSegmentLinear(p1, p2, thick, color);
/// Draw spline segment: B-Spline, 4 points
void DrawSplineSegmentBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, double thick, Color color) => raw.DrawSplineSegmentBasis(p1, p2, p3, p4, thick, color);
/// Draw spline segment: Catmull-Rom, 4 points
void DrawSplineSegmentCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, double thick, Color color) => raw.DrawSplineSegmentCatmullRom(p1, p2, p3, p4, thick, color);
/// Draw spline segment: Quadratic Bezier, 2 points, 1 control point
void DrawSplineSegmentBezierQuadratic(Vector2 p1, Vector2 c2, Vector2 p3, double thick, Color color) => raw.DrawSplineSegmentBezierQuadratic(p1, c2, p3, thick, color);
/// Draw spline segment: Cubic Bezier, 2 points, 2 control points
void DrawSplineSegmentBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, double thick, Color color) => raw.DrawSplineSegmentBezierCubic(p1, c2, c3, p4, thick, color);

// Spline segment point evaluation functions, for a given t [0.0f .. 1.0f]
/// Get (evaluate) spline point: Linear
Vector2 GetSplinePointLinear(Vector2 startPos, Vector2 endPos, double t) => raw.GetSplinePointLinear(startPos, endPos, t);
/// Get (evaluate) spline point: B-Spline
Vector2 GetSplinePointBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, double t) => raw.GetSplinePointBasis(p1, p2, p3, p4, t);
/// Get (evaluate) spline point: Catmull-Rom
Vector2 GetSplinePointCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, double t) => raw.GetSplinePointCatmullRom(p1, p2, p3, p4, t);
/// Get (evaluate) spline point: Quadratic Bezier
Vector2 GetSplinePointBezierQuad(Vector2 p1, Vector2 c2, Vector2 p3, double t) => raw.GetSplinePointBezierQuad(p1, c2, p3, t);
/// Get (evaluate) spline point: Cubic Bezier
Vector2 GetSplinePointBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, double t) => raw.GetSplinePointBezierCubic(p1, c2, c3, p4, t);

// Basic shapes collision detection functions
/// Check collision between two rectangles
bool CheckCollisionRecs(Rectangle rec1, Rectangle rec2) => raw.CheckCollisionRecs(rec1, rec2);
/// Check collision between two circles
bool CheckCollisionCircles(Vector2 center1, double radius1, Vector2 center2, double radius2) => raw.CheckCollisionCircles(center1, radius1, center2, radius2);
/// Check collision between circle and rectangle
bool CheckCollisionCircleRec(Vector2 center, double radius, Rectangle rec) => raw.CheckCollisionCircleRec(center, radius, rec);
/// Check if circle collides with a line created betweeen two points [p1] and [p2]
bool CheckCollisionCircleLine(Vector2 center, double radius, Vector2 p1, Vector2 p2) => raw.CheckCollisionCircleLine(center, radius, p1, p2);
/// Check if point is inside rectangle
bool CheckCollisionPointRec(Vector2 point, Rectangle rec) => raw.CheckCollisionPointRec(point, rec);
/// Check if point is inside circle
bool CheckCollisionPointCircle(Vector2 point, Vector2 center, double radius) => raw.CheckCollisionPointCircle(point, center, radius);
/// Check if point is inside a triangle
bool CheckCollisionPointTriangle(Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3) => raw.CheckCollisionPointTriangle(point, p1, p2, p3);
/// Check if point belongs to line created between two points [p1] and [p2] with defined margin in pixels [threshold]
bool CheckCollisionPointLine(Vector2 point, Vector2 p1, Vector2 p2, int threshold) => raw.CheckCollisionPointLine(point, p1, p2, threshold);
/// Check if point is within a polygon described by array of vertices
bool CheckCollisionPointPoly(Vector2 point, List<Vector2> points, int pointCount) => raw.CheckCollisionPointPoly(point, points, pointCount);
/// Check the collision between two lines defined by two points each, returns collision point by reference
bool CheckCollisionLines(Vector2 startPos1, Vector2 endPos1, Vector2 startPos2, Vector2 endPos2, List<Vector2> collisionPoint) => raw.CheckCollisionLines(startPos1, endPos1, startPos2, endPos2, collisionPoint);
/// Get collision rectangle for two rectangles collision
Rectangle GetCollisionRec(Rectangle rec1, Rectangle rec2) => raw.GetCollisionRec(rec1, rec2);


