// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'text_proxy.dart' as proxy;
import 'dart:typed_data';
import 'structs.dart';

// Font loading/unloading functions
/// Get the default Font
const GetFontDefault = proxy.GetFontDefault;
/// Load font from file into GPU memory (VRAM)
const LoadFont = proxy.LoadFont;
/// Load font from file with extended parameters, use NULL for codepoints and 0 for codepointCount to load the default character set, font size is provided in pixels height
const LoadFontEx = proxy.LoadFontEx;
/// Load font from Image (XNA style)
const LoadFontFromImage = proxy.LoadFontFromImage;
/// Load font from memory buffer, fileType refers to extension: i.e. '.ttf'
const LoadFontFromMemory = proxy.LoadFontFromMemory;
/// Check if a font is valid (font data loaded, WARNING: GPU texture not checked)
const IsFontValid = proxy.IsFontValid;
/// Load font data for further use
const LoadFontData = proxy.LoadFontData;
/// Generate image font atlas using chars info
const GenImageFontAtlas = proxy.GenImageFontAtlas;
/// Unload font chars info data (RAM)
const UnloadFontData = proxy.UnloadFontData;
/// Unload font from GPU memory (VRAM)
const UnloadFont = proxy.UnloadFont;
/// Export font as code file, returns true on success
const ExportFontAsCode = proxy.ExportFontAsCode;

// Text drawing functions
/// Draw current FPS
void DrawFPS(int posX, int posY) => raw.DrawFPS(posX, posY);
/// Draw text (using default font)
const DrawText = proxy.DrawText;
/// Draw text using font and additional parameters
const DrawTextEx = proxy.DrawTextEx;
/// Draw text using Font and pro parameters (rotation)
const DrawTextPro = proxy.DrawTextPro;
/// Draw one character (codepoint)
const DrawTextCodepoint = proxy.DrawTextCodepoint;
/// Draw multiple character (codepoint)
const DrawTextCodepoints = proxy.DrawTextCodepoints;

// Text font info functions
/// Set vertical line spacing when drawing with line-breaks
void SetTextLineSpacing(int spacing) => raw.SetTextLineSpacing(spacing);
/// Measure string width for default font
const MeasureText = proxy.MeasureText;
/// Measure string size for Font
const MeasureTextEx = proxy.MeasureTextEx;
/// Measure string size for an existing array of codepoints for Font
const MeasureTextCodepoints = proxy.MeasureTextCodepoints;
/// Get glyph index position in font for a codepoint (unicode character), fallback to '?' if not found
const GetGlyphIndex = proxy.GetGlyphIndex;
/// Get glyph font info data for a codepoint (unicode character), fallback to '?' if not found
const GetGlyphInfo = proxy.GetGlyphInfo;
/// Get glyph rectangle in font atlas for a codepoint (unicode character), fallback to '?' if not found
const GetGlyphAtlasRec = proxy.GetGlyphAtlasRec;

// Text codepoints management functions (unicode characters)
/// Load UTF-8 text encoded from codepoints array
const LoadUTF8 = proxy.LoadUTF8;
/// Unload UTF-8 text encoded from codepoints array
const UnloadUTF8 = proxy.UnloadUTF8;
/// Load all codepoints from a UTF-8 text string, codepoints count returned by parameter
const LoadCodepoints = proxy.LoadCodepoints;
/// Unload codepoints data from memory
const UnloadCodepoints = proxy.UnloadCodepoints;
/// Get total number of codepoints in a UTF-8 encoded string
const GetCodepointCount = proxy.GetCodepointCount;
/// Get next codepoint in a UTF-8 encoded string, 0x3f('?') is returned on failure
const GetCodepoint = proxy.GetCodepoint;
/// Get next codepoint in a UTF-8 encoded string, 0x3f('?') is returned on failure
const GetCodepointNext = proxy.GetCodepointNext;
/// Get previous codepoint in a UTF-8 encoded string, 0x3f('?') is returned on failure
const GetCodepointPrevious = proxy.GetCodepointPrevious;
/// Encode one codepoint into UTF-8 byte array (array length returned as parameter)
const CodepointToUTF8 = proxy.CodepointToUTF8;

// Text strings management functions (no UTF-8 strings, only byte chars)
// WARNING 1: Most of these functions use internal static buffers[], it's recommended to store returned data on user-side for re-use
// WARNING 2: Some functions allocate memory internally for the returned strings, those strings must be freed by user using MemFree()
/// Load text as separate lines ('\n')
const LoadTextLines = proxy.LoadTextLines;
/// Unload text lines
const UnloadTextLines = proxy.UnloadTextLines;
/// Copy one string to another, returns bytes copied
const TextCopy = proxy.TextCopy;
/// Check if two text string are equal
const TextIsEqual = proxy.TextIsEqual;
/// Get text length, checks for '\0' ending
const TextLength = proxy.TextLength;
/// Text formatting with variables (sprintf() style)
const TextFormat = proxy.TextFormat;
/// Get a piece of a text string
const TextSubtext = proxy.TextSubtext;
/// Remove text spaces, concat words
const TextRemoveSpaces = proxy.TextRemoveSpaces;
/// Get text between two strings
const GetTextBetween = proxy.GetTextBetween;
/// Replace text string with new string
const TextReplace = proxy.TextReplace;
/// Replace text string with new string, memory must be MemFree()
const TextReplaceAlloc = proxy.TextReplaceAlloc;
/// Replace text between two specific strings
const TextReplaceBetween = proxy.TextReplaceBetween;
/// Replace text between two specific strings, memory must be MemFree()
const TextReplaceBetweenAlloc = proxy.TextReplaceBetweenAlloc;
/// Insert text in a defined byte position
const TextInsert = proxy.TextInsert;
/// Insert text in a defined byte position, memory must be MemFree()
const TextInsertAlloc = proxy.TextInsertAlloc;
/// Join text strings with delimiter
const TextJoin = proxy.TextJoin;
/// Split text into multiple strings, using MAX_TEXTSPLIT_COUNT static strings
const TextSplit = proxy.TextSplit;
/// Append text at specific position and move cursor
const TextAppend = proxy.TextAppend;
/// Find first text occurrence within a string, -1 if not found
const TextFindIndex = proxy.TextFindIndex;
/// Get upper case version of provided string
const TextToUpper = proxy.TextToUpper;
/// Get lower case version of provided string
const TextToLower = proxy.TextToLower;
/// Get Pascal case notation version of provided string
const TextToPascal = proxy.TextToPascal;
/// Get Snake case notation version of provided string
const TextToSnake = proxy.TextToSnake;
/// Get Camel case notation version of provided string
const TextToCamel = proxy.TextToCamel;
/// Get integer value from text
const TextToInteger = proxy.TextToInteger;
/// Get float value from text
const TextToFloat = proxy.TextToFloat;


