// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import 'textures_proxy.dart' as proxy;
import 'structs.dart';

// Image loading functions
// NOTE: These functions do not require GPU access
/// Load image from file into CPU memory (RAM)
Image LoadImage(String fileName) => raw.LoadImage(fileName);
/// Load image from RAW file data
Image LoadImageRaw(String fileName, int width, int height, int format, int headerSize) => raw.LoadImageRaw(fileName, width, height, format, headerSize);
/// Load image sequence from file (frames appended to image.data)
Image LoadImageAnim(String fileName, List<int> frames) => raw.LoadImageAnim(fileName, frames);
/// Load image sequence from memory buffer
Image LoadImageAnimFromMemory(String fileType, String fileData, int dataSize, List<int> frames) => raw.LoadImageAnimFromMemory(fileType, fileData, dataSize, frames);
/// Load image from memory buffer, fileType refers to extension: i.e. '.png'
Image LoadImageFromMemory(String fileType, String fileData, int dataSize) => raw.LoadImageFromMemory(fileType, fileData, dataSize);
/// Load image from GPU texture data
Image LoadImageFromTexture(Texture2D texture) => raw.LoadImageFromTexture(texture);
/// Load image from screen buffer and (screenshot)
Image LoadImageFromScreen() => raw.LoadImageFromScreen();
/// Check if an image is valid (data and parameters)
bool IsImageValid(Image image) => raw.IsImageValid(image);
/// Unload image from CPU memory (RAM)
void UnloadImage(Image image) => raw.UnloadImage(image);
/// Export image data to file, returns true on success
bool ExportImage(Image image, String fileName) => raw.ExportImage(image, fileName);
/// Export image to memory buffer, memory must be MemFree()
String ExportImageToMemory(Image image, String fileType, List<int> fileSize) => raw.ExportImageToMemory(image, fileType, fileSize);
/// Export image as code file defining an array of bytes, returns true on success
bool ExportImageAsCode(Image image, String fileName) => raw.ExportImageAsCode(image, fileName);

// Image generation functions
/// Generate image: plain color
Image GenImageColor(int width, int height, Color color) => raw.GenImageColor(width, height, color);
/// Generate image: linear gradient, direction in degrees [0..360], 0=Vertical gradient
Image GenImageGradientLinear(int width, int height, int direction, Color start, Color end) => raw.GenImageGradientLinear(width, height, direction, start, end);
/// Generate image: radial gradient
Image GenImageGradientRadial(int width, int height, double density, Color inner, Color outer) => raw.GenImageGradientRadial(width, height, density, inner, outer);
/// Generate image: square gradient
Image GenImageGradientSquare(int width, int height, double density, Color inner, Color outer) => raw.GenImageGradientSquare(width, height, density, inner, outer);
/// Generate image: checked
Image GenImageChecked(int width, int height, int checksX, int checksY, Color col1, Color col2) => raw.GenImageChecked(width, height, checksX, checksY, col1, col2);
/// Generate image: white noise
Image GenImageWhiteNoise(int width, int height, double factor) => raw.GenImageWhiteNoise(width, height, factor);
/// Generate image: perlin noise
Image GenImagePerlinNoise(int width, int height, int offsetX, int offsetY, double scale) => raw.GenImagePerlinNoise(width, height, offsetX, offsetY, scale);
/// Generate image: cellular algorithm, bigger tileSize means bigger cells
Image GenImageCellular(int width, int height, int tileSize) => raw.GenImageCellular(width, height, tileSize);
/// Generate image: grayscale image from text data
Image GenImageText(int width, int height, String text) => raw.GenImageText(width, height, text);

// Image manipulation functions
/// Create an image duplicate (useful for transformations)
Image ImageCopy(Image image) => raw.ImageCopy(image);
/// Create an image from another image piece
Image ImageFromImage(Image image, Rectangle rec) => raw.ImageFromImage(image, rec);
/// Create an image from a selected channel of another image (GRAYSCALE)
Image ImageFromChannel(Image image, int selectedChannel) => raw.ImageFromChannel(image, selectedChannel);
/// Create an image from text (default font)
Image ImageText(String text, int fontSize, Color color) => raw.ImageText(text, fontSize, color);
/// Create an image from text (custom sprite font)
Image ImageTextEx(Font font, String text, double fontSize, double spacing, Color tint) => raw.ImageTextEx(font, text, fontSize, spacing, tint);
/// Convert image data to desired format
void ImageFormat(List<Image> image, int newFormat) => raw.ImageFormat(image, newFormat);
/// Convert image to POT (power-of-two)
void ImageToPOT(List<Image> image, Color fill) => raw.ImageToPOT(image, fill);
/// Crop an image to a defined rectangle
void ImageCrop(List<Image> image, Rectangle crop) => raw.ImageCrop(image, crop);
/// Crop image depending on alpha value
void ImageAlphaCrop(List<Image> image, double threshold) => raw.ImageAlphaCrop(image, threshold);
/// Clear alpha channel to desired color
void ImageAlphaClear(List<Image> image, Color color, double threshold) => raw.ImageAlphaClear(image, color, threshold);
/// Apply alpha mask to image
void ImageAlphaMask(List<Image> image, Image alphaMask) => raw.ImageAlphaMask(image, alphaMask);
/// Premultiply alpha channel
void ImageAlphaPremultiply(List<Image> image) => raw.ImageAlphaPremultiply(image);
/// Apply Gaussian blur using a box blur approximation
void ImageBlurGaussian(List<Image> image, int blurSize) => raw.ImageBlurGaussian(image, blurSize);
/// Apply custom square convolution kernel to image
void ImageKernelConvolution(List<Image> image, List<double> kernel, int kernelSize) => raw.ImageKernelConvolution(image, kernel, kernelSize);
/// Resize image (Bicubic scaling algorithm)
void ImageResize(List<Image> image, int newWidth, int newHeight) => raw.ImageResize(image, newWidth, newHeight);
/// Resize image (Nearest-Neighbor scaling algorithm)
void ImageResizeNN(List<Image> image, int newWidth, int newHeight) => raw.ImageResizeNN(image, newWidth, newHeight);
/// Resize canvas and fill with color
void ImageResizeCanvas(List<Image> image, int newWidth, int newHeight, int offsetX, int offsetY, Color fill) => raw.ImageResizeCanvas(image, newWidth, newHeight, offsetX, offsetY, fill);
/// Compute all mipmap levels for a provided image
void ImageMipmaps(List<Image> image) => raw.ImageMipmaps(image);
/// Dither image data to 16bpp or lower (Floyd-Steinberg dithering)
void ImageDither(List<Image> image, int rBpp, int gBpp, int bBpp, int aBpp) => raw.ImageDither(image, rBpp, gBpp, bBpp, aBpp);
/// Flip image vertically
void ImageFlipVertical(List<Image> image) => raw.ImageFlipVertical(image);
/// Flip image horizontally
void ImageFlipHorizontal(List<Image> image) => raw.ImageFlipHorizontal(image);
/// Rotate image by input angle in degrees (-359 to 359)
void ImageRotate(List<Image> image, int degrees) => raw.ImageRotate(image, degrees);
/// Rotate image clockwise 90deg
void ImageRotateCW(List<Image> image) => raw.ImageRotateCW(image);
/// Rotate image counter-clockwise 90deg
void ImageRotateCCW(List<Image> image) => raw.ImageRotateCCW(image);
/// Modify image color: tint
void ImageColorTint(List<Image> image, Color color) => raw.ImageColorTint(image, color);
/// Modify image color: invert
void ImageColorInvert(List<Image> image) => raw.ImageColorInvert(image);
/// Modify image color: grayscale
void ImageColorGrayscale(List<Image> image) => raw.ImageColorGrayscale(image);
/// Modify image color: contrast (-100 to 100)
void ImageColorContrast(List<Image> image, double contrast) => raw.ImageColorContrast(image, contrast);
/// Modify image color: brightness (-255 to 255)
void ImageColorBrightness(List<Image> image, int brightness) => raw.ImageColorBrightness(image, brightness);
/// Modify image color: replace color
void ImageColorReplace(List<Image> image, Color color, Color replace) => raw.ImageColorReplace(image, color, replace);
/// Load color data from image as a Color array (RGBA - 32bit)
List<Color> LoadImageColors(Image image) => raw.LoadImageColors(image);
/// Load colors palette from image as a Color array (RGBA - 32bit)
List<Color> LoadImagePalette(Image image, int maxPaletteSize, List<int> colorCount) => raw.LoadImagePalette(image, maxPaletteSize, colorCount);
/// Unload color data loaded with LoadImageColors()
void UnloadImageColors(List<Color> colors) => raw.UnloadImageColors(colors);
/// Unload colors palette loaded with LoadImagePalette()
void UnloadImagePalette(List<Color> colors) => raw.UnloadImagePalette(colors);
/// Get image alpha border rectangle
Rectangle GetImageAlphaBorder(Image image, double threshold) => raw.GetImageAlphaBorder(image, threshold);
/// Get image pixel color at (x, y) position
Color GetImageColor(Image image, int x, int y) => raw.GetImageColor(image, x, y);

// Image drawing functions
// NOTE: Image software-rendering functions (CPU)
/// Clear image background with given color
void ImageClearBackground(List<Image> dst, Color color) => raw.ImageClearBackground(dst, color);
/// Draw pixel within an image
void ImageDrawPixel(List<Image> dst, int posX, int posY, Color color) => raw.ImageDrawPixel(dst, posX, posY, color);
/// Draw pixel within an image (Vector version)
void ImageDrawPixelV(List<Image> dst, Vector2 position, Color color) => raw.ImageDrawPixelV(dst, position, color);
/// Draw line within an image
void ImageDrawLine(List<Image> dst, int startPosX, int startPosY, int endPosX, int endPosY, Color color) => raw.ImageDrawLine(dst, startPosX, startPosY, endPosX, endPosY, color);
/// Draw line within an image (Vector version)
void ImageDrawLineV(List<Image> dst, Vector2 start, Vector2 end, Color color) => raw.ImageDrawLineV(dst, start, end, color);
/// Draw a line defining thickness within an image
void ImageDrawLineEx(List<Image> dst, Vector2 start, Vector2 end, int thick, Color color) => raw.ImageDrawLineEx(dst, start, end, thick, color);
/// Draw a filled circle within an image
void ImageDrawCircle(List<Image> dst, int centerX, int centerY, int radius, Color color) => raw.ImageDrawCircle(dst, centerX, centerY, radius, color);
/// Draw a filled circle within an image (Vector version)
void ImageDrawCircleV(List<Image> dst, Vector2 center, int radius, Color color) => raw.ImageDrawCircleV(dst, center, radius, color);
/// Draw circle outline within an image
void ImageDrawCircleLines(List<Image> dst, int centerX, int centerY, int radius, Color color) => raw.ImageDrawCircleLines(dst, centerX, centerY, radius, color);
/// Draw circle outline within an image (Vector version)
void ImageDrawCircleLinesV(List<Image> dst, Vector2 center, int radius, Color color) => raw.ImageDrawCircleLinesV(dst, center, radius, color);
/// Draw rectangle within an image
void ImageDrawRectangle(List<Image> dst, int posX, int posY, int width, int height, Color color) => raw.ImageDrawRectangle(dst, posX, posY, width, height, color);
/// Draw rectangle within an image (Vector version)
void ImageDrawRectangleV(List<Image> dst, Vector2 position, Vector2 size, Color color) => raw.ImageDrawRectangleV(dst, position, size, color);
/// Draw rectangle within an image
void ImageDrawRectangleRec(List<Image> dst, Rectangle rec, Color color) => raw.ImageDrawRectangleRec(dst, rec, color);
/// Draw rectangle lines within an image
void ImageDrawRectangleLines(List<Image> dst, Rectangle rec, int thick, Color color) => raw.ImageDrawRectangleLines(dst, rec, thick, color);
/// Draw triangle within an image
void ImageDrawTriangle(List<Image> dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color) => raw.ImageDrawTriangle(dst, v1, v2, v3, color);
/// Draw triangle with interpolated colors within an image
void ImageDrawTriangleEx(List<Image> dst, Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3) => raw.ImageDrawTriangleEx(dst, v1, v2, v3, c1, c2, c3);
/// Draw triangle outline within an image
void ImageDrawTriangleLines(List<Image> dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color) => raw.ImageDrawTriangleLines(dst, v1, v2, v3, color);
/// Draw a triangle fan defined by points within an image (first vertex is the center)
void ImageDrawTriangleFan(List<Image> dst, List<Vector2> points, int pointCount, Color color) => raw.ImageDrawTriangleFan(dst, points, pointCount, color);
/// Draw a triangle strip defined by points within an image
void ImageDrawTriangleStrip(List<Image> dst, List<Vector2> points, int pointCount, Color color) => raw.ImageDrawTriangleStrip(dst, points, pointCount, color);
/// Draw a source image within a destination image (tint applied to source)
void ImageDraw(List<Image> dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint) => raw.ImageDraw(dst, src, srcRec, dstRec, tint);
/// Draw text (using default font) within an image (destination)
void ImageDrawText(List<Image> dst, String text, int posX, int posY, int fontSize, Color color) => raw.ImageDrawText(dst, text, posX, posY, fontSize, color);
/// Draw text (custom sprite font) within an image (destination)
void ImageDrawTextEx(List<Image> dst, Font font, String text, Vector2 position, double fontSize, double spacing, Color tint) => raw.ImageDrawTextEx(dst, font, text, position, fontSize, spacing, tint);

// Texture loading functions
// NOTE: These functions require GPU access
/// Load texture from file into GPU memory (VRAM)
Texture2D LoadTexture(String fileName) => raw.LoadTexture(fileName);
/// Load texture from image data
Texture2D LoadTextureFromImage(Image image) => raw.LoadTextureFromImage(image);
/// Load cubemap from image, multiple image cubemap layouts supported
TextureCubemap LoadTextureCubemap(Image image, int layout) => raw.LoadTextureCubemap(image, layout);
/// Load texture for rendering (framebuffer)
RenderTexture2D LoadRenderTexture(int width, int height) => raw.LoadRenderTexture(width, height);
/// Check if a texture is valid (loaded in GPU)
bool IsTextureValid(Texture2D texture) => raw.IsTextureValid(texture);
/// Unload texture from GPU memory (VRAM)
void UnloadTexture(Texture2D texture) => raw.UnloadTexture(texture);
/// Check if a render texture is valid (loaded in GPU)
bool IsRenderTextureValid(RenderTexture2D target) => raw.IsRenderTextureValid(target);
/// Unload render texture from GPU memory (VRAM)
void UnloadRenderTexture(RenderTexture2D target) => raw.UnloadRenderTexture(target);
/// Update GPU texture with new data (pixels should be able to fill texture)
void UpdateTexture(Texture2D texture, int pixels) => raw.UpdateTexture(texture, pixels);
/// Update GPU texture rectangle with new data (pixels and rec should fit in texture)
void UpdateTextureRec(Texture2D texture, Rectangle rec, int pixels) => raw.UpdateTextureRec(texture, rec, pixels);

// Texture configuration functions
/// Generate GPU mipmaps for a texture
void GenTextureMipmaps(List<Texture2D> texture) => raw.GenTextureMipmaps(texture);
/// Set texture scaling filter mode
void SetTextureFilter(Texture2D texture, int filter) => raw.SetTextureFilter(texture, filter);
/// Set texture wrapping mode
void SetTextureWrap(Texture2D texture, int wrap) => raw.SetTextureWrap(texture, wrap);

// Texture drawing functions
/// Draw a Texture2D
void DrawTexture(Texture2D texture, int posX, int posY, Color tint) => raw.DrawTexture(texture, posX, posY, tint);
/// Draw a Texture2D with position defined as Vector2
void DrawTextureV(Texture2D texture, Vector2 position, Color tint) => raw.DrawTextureV(texture, position, tint);
/// Draw a Texture2D with extended parameters
void DrawTextureEx(Texture2D texture, Vector2 position, double rotation, double scale, Color tint) => raw.DrawTextureEx(texture, position, rotation, scale, tint);
/// Draw a part of a texture defined by a rectangle
void DrawTextureRec(Texture2D texture, Rectangle source, Vector2 position, Color tint) => raw.DrawTextureRec(texture, source, position, tint);
/// Draw a part of a texture defined by a rectangle with 'pro' parameters
void DrawTexturePro(Texture2D texture, Rectangle source, Rectangle dest, Vector2 origin, double rotation, Color tint) => raw.DrawTexturePro(texture, source, dest, origin, rotation, tint);
/// Draws a texture (or part of it) that stretches or shrinks nicely
void DrawTextureNPatch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle dest, Vector2 origin, double rotation, Color tint) => raw.DrawTextureNPatch(texture, nPatchInfo, dest, origin, rotation, tint);

// Color/pixel related functions
/// Check if two colors are equal
bool ColorIsEqual(Color col1, Color col2) => raw.ColorIsEqual(col1, col2);
/// Get color with alpha applied, alpha goes from 0.0f to 1.0f
Color Fade(Color color, double alpha) => raw.Fade(color, alpha);
/// Get hexadecimal value for a Color (0xRRGGBBAA)
int ColorToInt(Color color) => raw.ColorToInt(color);
/// Get Color normalized as float [0..1]
Vector4 ColorNormalize(Color color) => raw.ColorNormalize(color);
/// Get Color from normalized values [0..1]
Color ColorFromNormalized(Vector4 normalized) => raw.ColorFromNormalized(normalized);
/// Get HSV values for a Color, hue [0..360], saturation/value [0..1]
Vector3 ColorToHSV(Color color) => raw.ColorToHSV(color);
/// Get a Color from HSV values, hue [0..360], saturation/value [0..1]
Color ColorFromHSV(double hue, double saturation, double value) => raw.ColorFromHSV(hue, saturation, value);
/// Get color multiplied with another color
Color ColorTint(Color color, Color tint) => raw.ColorTint(color, tint);
/// Get color with brightness correction, brightness factor goes from -1.0f to 1.0f
Color ColorBrightness(Color color, double factor) => raw.ColorBrightness(color, factor);
/// Get color with contrast correction, contrast values between -1.0f and 1.0f
Color ColorContrast(Color color, double contrast) => raw.ColorContrast(color, contrast);
/// Get color with alpha applied, alpha goes from 0.0f to 1.0f
Color ColorAlpha(Color color, double alpha) => raw.ColorAlpha(color, alpha);
/// Get src alpha-blended into dst color with tint
Color ColorAlphaBlend(Color dst, Color src, Color tint) => raw.ColorAlphaBlend(dst, src, tint);
/// Get color lerp interpolation between two colors, factor [0.0f..1.0f]
Color ColorLerp(Color color1, Color color2, double factor) => raw.ColorLerp(color1, color2, factor);
/// Get Color structure from hexadecimal value
Color GetColor(int hexValue) => raw.GetColor(hexValue);
/// Get Color from a source pixel pointer of certain format
Color GetPixelColor(int srcPtr, int format) => raw.GetPixelColor(srcPtr, format);
/// Set color formatted into destination pixel pointer
void SetPixelColor(int dstPtr, Color color, int format) => raw.SetPixelColor(dstPtr, color, format);
/// Get pixel data size in bytes for certain format
int GetPixelDataSize(int width, int height, int format) => raw.GetPixelDataSize(width, height, format);


