/**
 * 基本思路就是将 C 函数原型转换为 Dart 函数签名
 * 
 * 如果 proxy 文件里面有对应的函数实现，则转发给 proxy，否则转发给 raw。
 * 
 * 
 */

import 'dart:io';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:c_proto_parser/c_proto_parser.dart';

final modules = <String, ({String deps})>{
  'core': (
    deps: """
import 'raylib_const.dart';
import 'structs.dart';
import 'dart:typed_data';
""",
  ),
  'shapes': (
    deps: """
import 'structs.dart';
""",
  ),
  'textures': (
    deps: """
import 'dart:typed_data';
import 'raylib_const.dart';
import 'structs.dart';
""",
  ),
  'text': (
    deps: """
import 'dart:typed_data';
import 'structs.dart';
""",
  ),
  'models': (
    deps: """
import 'dart:typed_data';
import 'raylib_const.dart';
import 'structs.dart';
""",
  ),
  'audio': (
    deps: """
import 'dart:typed_data';
import 'structs.dart';
""",
  ),
};

String toDartType(CType type) {
  if (type.isVoid) return 'void';
  if (type.base == 'void' && type.pointerDepth == 1) return 'int';
  if (type.base.contains('char') && type.pointerDepth == 1) return 'String';
  if (type.pointerDepth > 0) {
    return 'List<${toDartType(type.copyWith(pointerDepth: type.pointerDepth - 1))}>';
  }

  return switch (type.base) {
    'int' || 'unsigned int' || 'short' || 'long' => 'int',
    'float' || 'double' => 'double',
    'bool' || '_Bool' => 'bool',
    'variadic' => 'List<Object>',
    _ => type.base,
  };
}

void main() async {
  for (final MapEntry(key: name, value: overrides) in modules.entries) {
    final api = await apiOf(name);
    final proxy = await proxyOf(name);
    final rule = ApiMapRule(
      topLevelFunctionNamesFromSource(proxy),
    );
    final dartApi = translate(api, rule);
    await generateModule(name, overrides.deps, dartApi);
  }
}

Future<void> generateModule(String module, String deps, String dartApi) async {
  final file = File('lib/src/$module.g.dart');
  await file.writeAsString("""
// generated by tools/generate_api.dart, do not edit by hand
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'raylib.g.dart' as raw;
import '${module}_proxy.dart' as proxy;
$deps
$dartApi
""");
}

Future<String> apiOf(String module) async {
  final file = File('cheatsheet/$module.c');
  return file.readAsString();
}

Future<String> proxyOf(String module) async {
  final file = File('lib/src/${module}_proxy.dart');
  if (!file.existsSync()) return '';
  return file.readAsString();
}

/// Splits a line into a comment and code part
/// void f(int a); // This is a comment => ('void f(int a);', 'This is a comment')
(String, String) splitComment(String line) {
  final commentIndex = line.indexOf('//');
  if (commentIndex == -1) return (line.trim(), '');
  final codePart = line.substring(0, commentIndex).trim();
  final commentPart = line.substring(commentIndex + 2).trim();
  return (codePart, commentPart);
}

enum LineType {
  code,
  comment,
  empty;

  factory LineType.of(String line) {
    final trimmed = line.trim();
    if (trimmed.isEmpty) return .empty;
    if (trimmed.startsWith('//')) return .comment;
    return .code;
  }
}

class ApiMapRule {
  final Set<String> proxyFunctions;

  ApiMapRule(this.proxyFunctions);

  String call(String api) {
    final function = parseCFunctionPrototype(api);
    final func = function.name;
    if (!proxyFunctions.contains(func)) {
      final returnType = toDartType(function.returnType);
      final interfaceFunc =
          '$returnType $func(${funcParamList(function.params)})';
      return '$interfaceFunc => raw.$func(${funcCall(function.params)});';
    }
    return 'const $func = proxy.$func;';
  }

  String funcCall(List<CParam> params) {
    if (params.length == 1 && params[0].type.isVoid) {
      return '';
    }
    return params.map((p) => paramName(p.name)).join(', ');
  }

  String paramName(String name) => name == '...' ? 'args' : name;

  String dartParamNames(String interface) {
    final result = parseString(
      content: 'external $interface;',
      throwIfDiagnostics: false,
    );
    final declaration = result.unit.declarations
        .whereType<FunctionDeclaration>()
        .single;
    final params = declaration.functionExpression.parameters?.parameters ?? [];
    return params.map((p) => p.name?.lexeme).whereType<String>().join(', ');
  }

  String funcParamList(List<CParam> params) {
    if (params.length == 1 && params[0].type.isVoid) {
      return '';
    }
    return params
        .map((p) => '${toDartType(p.type)} ${paramName(p.name)}')
        .join(', ');
  }
}

String translate(String source, ApiMapRule rule) {
  final lines = source.split('\n');
  final translatedLines = lines.map(
    (line) => switch (LineType.of(line)) {
      // dart format off
      .code    => () {
                    final (codePart, commentPart) = splitComment(line);
                    return '/// $commentPart\n${rule(codePart)}';
                  }(),
      .comment => line.trim(),
      .empty   => line,
      // dart format on
    },
  );
  return translatedLines.join('\n');
}

Set<String> topLevelFunctionNamesFromSource(String source) {
  final result = parseString(content: source, throwIfDiagnostics: false);

  return {
    for (final declaration in result.unit.declarations)
      if (declaration is FunctionDeclaration) declaration.name.lexeme,
  };
}
